Bugfix: Adding bounds to wcs fitting
astropy/astropy pull request #10346
Opened 2020-05-12 19:41 UTC by ceb8

### Description

This pull request addresses three small bugs in `wcs.utils.fit_wcs_from_points`:
- Added bounds to the least square fit requiring that the fit CRPIX value be within the bounds of the input coordinate/pixel pairs. This prevents getting physically meaningless CRPIX fits like "-44811.23089933425  -40821.30343222443" .
- Corrected the pixel shape by adding 1 to each dimension because it is a subtraction of indices, not lengths.
- Moved the xp,xy assignment of the try/except so that they get assigned regardless.

The first two bugs are illustrated in the following code snippet:
![Screen Shot 2020-05-12 at 3 34 01 PM](https://user-images.githubusercontent.com/9406508/81737486-29f94b00-9466-11ea-8571-7df7f4eab09c.png)

And the corrected result is:
![Screen Shot 2020-05-12 at 3 36 50 PM](https://user-images.githubusercontent.com/9406508/81737653-6cbb2300-9466-11ea-9254-d5f7de5f1a14.png)

@cshanahan1 will want to look at this.

2020-05-12 19:41 UTC, pep8speaks commented
Hello @ceb8 :wave:! Thanks for opening this pull request, we are very grateful for your contribution! I'm a friendly :robot: that checks for style issues in this pull request, since this project follows the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guidelines. I've listed some small issues I found below, but please don't hesitate to ask if any of them are unclear!


* In the file [`astropy/wcs/utils.py`](https://github.com/astropy/astropy/blob/c556fe681edcfb0775dcdec35020791ab075d427/astropy/wcs/utils.py):

> [Line 1084:1](https://github.com/astropy/astropy/blob/c556fe681edcfb0775dcdec35020791ab075d427/astropy/wcs/utils.py#L1084): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-05-12 19:45 UTC, pllim commented
Need test(s) and change log. Thanks!

2020-05-13 17:48 UTC, ceb8 commented
@pllim Since you put this in the 4.1.1 milestone, I put my changelog entry in the 4.1 section, should I have put it in the 4.2 section instead?

I've added a test, and confirmed that it fails before the bugfix and passes after.

I'm also confused about the html-docs test error, it seems to be an error in running the codedocstyle command at all? Do you have any insite? Nothing I did should be affecting the docs.

2020-05-13 17:51 UTC, pllim commented
Rebase to get rid of the error.

As for change log, I am not sure. This PR is opened at a weird window of a release.

2020-05-13 20:44 UTC, ceb8 commented
@pllim Ok, I'll leave the changelog entry failing, and when this gets reviewed and is ready for merge I can put it in whatever the correct section is then.

2020-09-23 16:15 UTC, nden requested changes
Looks good!
I have a few style related requests and then this can be merged.
In addition to the comments, please go over the changes and add spaces between operators and after commas, basically conform to PEP8 style.
Thanks!

2020-09-23 16:15 UTC, nden commented on astropy/wcs/utils.py
> +    if ypmin==ypmax: ypmin, ypmax = ypmin-0.5, ypmax+0.5
Please split the above two lines so it's consistent with the rest of the package.

2020-09-30 16:06 UTC, ceb8 commented
@nden I believe I've addressed all your comments. And I moved the changelog entry to match the milestone.

2020-10-05 19:09 UTC, nden approved these changes

2020-10-05 19:09 UTC, merged