add wcs slices as argument to functions in wcsaxes
astropy/astropy pull request #10758
Opened 2020-09-22 16:14 UTC by cshanahan1

This fix is needed for https://github.com/aplpy/aplpy/pull/457

The contour plot function in aplpy doesn't allow >2D WCS, this fixes that by allowing WCS slices to be passed in to some of the functions in wcsaxes.

2020-09-22 16:34 UTC, pllim commented
I am leaning towards 4.2 until it is absolutely critical this needs to be backported. Need change log and test. Thanks!

2020-10-21 20:27 UTC, astrofrog requested changes
This makes sense, thanks! Could you add a changelog entry in the 4.2 section?

Ideally this would require a test, but let me know if you don't have time to add one.

2020-10-21 20:27 UTC, astrofrog commented on astropy/visualization/wcsaxes/core.py
> +            transform, coord_meta = transform_coord_meta_from_wcs(frame, self.frame_class, slices)
This should be ``slices=slices`` to be safe

2020-10-22 09:16 UTC, Cadair requested changes
I am not sure this change is needed. I don't think I see the advantage of adding new kwargs over applying the slice directly to the WCS object before it is passed to the method. (See my comment on the aplpy PR).

Let me know if I am missing something :)

2021-05-03 15:14 UTC, eteq commented
Since this hasn't made the feature freeze cutoff and is not a bug/docfix I'm re-milestoning to 5.0.

But @cshanahan1 might want to have a look at https://github.com/astropy/astropy/pull/10758#pullrequestreview-514522521 since it appears we have two votes, one for and one against... (which means @cshanahan1 might be able to be vote 3 :wink:)

2021-10-04 05:39 UTC, closed without merging