Fix WCSAxes bbox calculation
astropy/astropy pull request #10797
Opened 2020-10-04 12:42 UTC by dstansby

Fixes https://github.com/astropy/astropy/issues/10796.

Instead of just using the coordinate text boxes as the bounding bbox, make use of Matplotlib's method to calculate the tight bbox, but hand over the Text artists that form the custom coordinates.

This needs a test, and it also needs investigation and probably some more changes, as it slightly overdoes improvements
to tight layout:

![Figure_1](https://user-images.githubusercontent.com/6197628/95015865-5c8b2680-0647-11eb-838e-ddc30c53b563.png)

2020-10-05 19:53 UTC, dstansby commented
This was deceptively easy in the end, just needed to include the bbox of the actual axes instead of just the tick labels...

2020-10-05 20:00 UTC, pllim commented
Needs a change log. I'll let reviewers decide if a test is necessary.

2020-10-13 23:49 UTC, astrofrog commented
Thank for the fix! It looks like no tests cover this line - though I suspect they do, but it might just be that we don't report coverage from CircleCI?

2020-10-14 09:49 UTC, Cadair commented
The tests seem to be failing, otherwise looks good :+1:

2020-10-21 20:24 UTC, astrofrog requested changes
Thanks! Just a small comment below.

2020-10-21 20:24 UTC, astrofrog commented on astropy/visualization/wcsaxes/tests/test_misc.py
> +    assert ax_bbox.x0 == 11.38888888888889
This and the ones below should be assert_allclose

2020-10-23 10:31 UTC, astrofrog commented
@dstansby - do you have time to wrap this up? It would be good to get this fix in!

2020-10-23 13:03 UTC, dstansby commented
Not really, if someone wants to finish it feel free. I think the outstanding issue is that the bbox calaculation is matplotlib version dependent, so the test should be pinned to and only run on a single version of matplotlib.

2020-10-23 19:36 UTC, astrofrog commented on astropy/visualization/wcsaxes/tests/test_misc.py
> +NOT_MATPLOTLIB_33 = mpl_version.major != 3 or mpl_version.minor != 3
Can you make this ``MATPLOTLIB_33`` and write ``not MATPLOTLIB_33`` in the skipif below?

2020-10-23 19:37 UTC, Cadair commented on astropy/visualization/wcsaxes/tests/test_misc.py
> +NOT_MATPLOTLIB_33 = mpl_version.major != 3 or mpl_version.minor != 3
```suggestion
MATPLOTLIB_33 = mpl_version.major == 3 or mpl_version.minor == 3
```

2020-10-23 19:37 UTC, Cadair commented on astropy/visualization/wcsaxes/tests/test_misc.py
> +@pytest.mark.skipif('NOT_MATPLOTLIB_33')
```suggestion
@pytest.mark.skipif('not MATPLOTLIB_33')
```

2020-10-23 19:46 UTC, astrofrog approved these changes
Looks good, thanks @dstansby and @Cadair!

2020-10-23 21:46 UTC, merged