Add what's new for time performance improvements
astropy/astropy pull request #10938
Opened 2020-10-26 12:38 UTC by taldcroft

### Description

This pull request is to add what's new (4.2) for time performance improvements.

Fixes #<Issue Number>

2020-10-26 13:49 UTC, pllim requested changes
Thanks! Need some minor fixes.

I also wonder if we have benchmark that would show such improvements visually over at https://github.com/astropy/astropy-benchmarks/ . More of a personal curiosity, as we don't have a precedence of link to benchmarks from What's New.

2020-10-26 13:49 UTC, pllim commented on docs/time/index.rst
> +.. _time-fast-c-parser
```suggestion
.. _time-fast-c-parser:
```

2020-10-26 13:49 UTC, pllim commented on docs/whatsnew/4.2.rst
> +
Need a ref link for the section and then link to this section from TOC above.

2020-10-26 13:49 UTC, pllim commented on docs/whatsnew/4.2.rst
> +format like ``unix``, ``unix_tai`` or ``cxcsec`` was improved by a factor of 4.
Oxford comma! 😹 

```suggestion
format like ``unix``, ``unix_tai``, or ``cxcsec`` was improved by a factor of 4.
```

2020-10-27 03:17 UTC, pllim approved these changes
To speed things up, I applied my review as follow-up commits, so LGTM now. Thanks!

2020-10-27 08:57 UTC, taldcroft commented
@pllim - thanks for the cleanup, and sorry for not getting it right the first time. I don't get along with sphinx... and I always seem to forget that Oxford comma. :smile:

2020-10-27 08:57 UTC, merged