Adoptes use of new ERFA ecliptic transformation machinery
astropy/astropy pull request #11185
Opened 2020-12-22 14:06 UTC by homeboy445

### Description

Adopted the use of new ERFA ecliptic transformation machinery in ecliptic_transforms.py

Fixes #4873

2020-12-22 14:27 UTC, pllim commented
Thanks, will need a test and a change log, **but** before you proceed, let's wait for a review first, as the issue you are trying to fix is very old so I am not sure if it is still an issue or not...

2020-12-22 17:30 UTC, mhvk requested changes
@homeboy445 - thanks for applying the fix. Since @astrojuanlu basically said this was what was needed to be done, no problems there!  However, the code can be even simpler, and, more importantly, could you change the comment above the code, otherwise it will just confuse people! Suggestion inline.

2020-12-22 17:30 UTC, mhvk commented on astropy/coordinates/builtin_frames/ecliptic_transforms.py
>      # function and also brings the results closer to what other libraries
I think with the change we also need to adjust the comment, explaining why this function exists at all! Maybe
```
This code just calls ecm06, which uses the precession matrix according to the
IAU 2006 model, but leaves out nutation. This brings the results closer to what
other libraries give (see https://github.com/astropy/astropy/pull/6508).
```

2020-12-22 17:30 UTC, mhvk commented on astropy/coordinates/builtin_frames/ecliptic_transforms.py
> -    rbp = erfa.pmat06(jd1, jd2)
I would make this just a one-liner with
```
return erfa.ecm06(*get_jd12(equinix, 'tt'))
```

2020-12-23 14:20 UTC, pllim commented
Thanks for your continued patience, @homeboy445 ! Can you please squash all your commits into one commit, given that there is a merge commit in there anyway?

2020-12-23 15:09 UTC, pep8speaks commented
Hello @homeboy445 :wave:! It looks like you've made some changes in your pull request, so I've checked the code again for style.


* In the file [`astropy/coordinates/builtin_frames/ecliptic_transforms.py`](https://github.com/astropy/astropy/blob/f44dd2d41daf92972786542dae149814227507fa/astropy/coordinates/builtin_frames/ecliptic_transforms.py):

> [Line 28:1](https://github.com/astropy/astropy/blob/f44dd2d41daf92972786542dae149814227507fa/astropy/coordinates/builtin_frames/ecliptic_transforms.py#L28): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 0
> [Line 28:1](https://github.com/astropy/astropy/blob/f44dd2d41daf92972786542dae149814227507fa/astropy/coordinates/builtin_frames/ecliptic_transforms.py#L28): [E112](https://duckduckgo.com/?q=pep8%20E112) expected an indented block
> [Line 28:2](https://github.com/astropy/astropy/blob/f44dd2d41daf92972786542dae149814227507fa/astropy/coordinates/builtin_frames/ecliptic_transforms.py#L28): [E999](https://duckduckgo.com/?q=pep8%20E999) IndentationError: expected an indented block
> [Line 32:5](https://github.com/astropy/astropy/blob/f44dd2d41daf92972786542dae149814227507fa/astropy/coordinates/builtin_frames/ecliptic_transforms.py#L32): [E113](https://duckduckgo.com/?q=pep8%20E113) unexpected indentation

2020-12-29 17:20 UTC, astrojuanlu approved these changes
Looks good to me!

2020-12-29 20:07 UTC, mhvk approved these changes
Ah, I hadn't noticed the change was already made. All OK now. Thanks, @homeboy445!

2020-12-29 20:07 UTC, merged