Fixes so that models can more uniformly accept inputs with dim > 2.
astropy/astropy pull request #11435
Opened 2021-03-26 15:54 UTC by WilliamJamieson

### Description

Models involving rotations were crashing whenever inputs of dimension > 2 were passed. This was due to the base rotation model's evaluate function directly checking if the dimension of an array was exactly 2 in order to flatten the array. This is required due to a later matrix multiplication. This check was removed because flattening will not effect 1D arrays, all arrays >= 2D will need to be flattened in order to perform the matrix multiplication.

Fixes #11384 and Fixes spacetelescope/gwcs#89

2021-03-26 15:54 UTC, WilliamJamieson commented
Tagging @nden and @mcara.

2021-03-26 18:48 UTC, pllim requested changes
This does need a change log but let's hold off on that until after towncrier switch is done. I'll add a checkbox in the original post so you don't forget.

2021-03-26 18:48 UTC, pllim commented on astropy/modeling/tests/test_rotations.py
> +                                   [np.random.random((3,4  )) for _ in range(2)],
If you have to use random numbers, please use a seed so that it is reproducible. I would avoid any randomness altogether if possible.

2021-03-26 20:06 UTC, pllim commented
RTD failure is unrelated and addressed in #11437

2021-03-29 17:21 UTC, mcara approved these changes
I think this PR fixes the issue with dim>2 with rotation models. Thank you for investigating the root-cause!

2021-04-05 22:26 UTC, nden approved these changes

2021-04-05 22:30 UTC, pllim commented
Something is weird with the `CI / Python 3.8 with all optional dependencies (pull_request)` job but the mpldev and dev job failures are unrelated.

2021-04-06 11:53 UTC, nden commented
@pllim I rerun the tests and they pass now.

2021-04-06 11:53 UTC, merged