ENH: Paranormal distribution
astropy/astropy pull request #11457
Opened 2021-04-01 14:17 UTC by pllim

### Description

This pull request is to add paranormal distribution.

![Screenshot 2021-03-31 160903](https://user-images.githubusercontent.com/2090236/113307540-3fbc6c80-92d3-11eb-8643-5169f5045545.jpg)

![Screenshot 2021-03-31 160942](https://user-images.githubusercontent.com/2090236/113307552-43e88a00-92d3-11eb-9aa7-d2cafbe77eb5.jpg)

p.s. Ancient aliens are out of scope.

2021-04-01 14:49 UTC, hamogu commented
I appreciate that the bot gives advice to @pllim on how to skip the CI!

2021-04-01 15:22 UTC, eteq requested changes
One important suggestion inline. 

 As a broader comment, maybe we should adopt this as the default for uncertainties throughout astropy.  After all, super-natural is clearly better than a natural distribution for a given problem...

2021-04-01 15:28 UTC, pllim commented on astropy/uncertainty/distributions.py
> +        raise ValueError('oooOOOooOOoooo')
Great idea!

2021-04-01 15:30 UTC, pllim commented
It is unfortunate RTD is currently broken due to #11458 . So you will just have to trust the screenshots.

2021-04-01 18:33 UTC, dhomeier commented
I just realise we really should have put _Improving Support for Spectre_ as top-level functionality bullet point in the roadmap!

2021-04-01 23:16 UTC, mwcraig commented
> I just realise we really should have put Improving Support for Spectres 

I suppose spectres might be easier than spectra 🤔

2021-04-02 19:33 UTC, pllim commented
Alright, we got our fun. Until next year! 😉

2021-04-02 19:33 UTC, closed without merging