Add an important feature from IRAF
astropy/astropy pull request #11460
Opened 2021-04-01 16:58 UTC by eteq

To use, just do:
```
import astropy

astropy.flpr()
```
I think I got both the style of the documentation and the actual implementation right from the original version...

2021-04-01 17:39 UTC, barentsen requested changes

2021-04-01 17:39 UTC, barentsen commented on astropy/__init__.py
> +def flpr():
Great work! :+1:

Prayers to the gods of computing occasionally take a long time to be answered.  Can I suggest we make this an asynchronous function?
```suggestion
async def flpr():
```

2021-04-01 18:32 UTC, pllim reviewed
I think it should randomly throw a kernel panic.

2021-04-01 18:33 UTC, pllim commented
And based on https://www.noao.edu/kpno/manuals/ice/node7.html , might need to call it twice, just to be safe.

2021-04-01 19:17 UTC, eteq commented
Good points @pllim !  See https://github.com/astropy/astropy/pull/11460/commits/d25b1d14462dc6bcc8b519ca5af5ae7a1cfd7ccb where I added some code inspired by that link.

2021-04-01 22:59 UTC, pllim commented on astropy/__init__.py
> +        print('Abnormal termination of child process. Or something 🤷')
```suggestion
        print('PANIC in `/the/disco.e\': Abnormal termination of child process. Or something 🤷')
```

2021-04-02 19:33 UTC, pllim commented
Alright, we got our fun. Until next year! 😉

2021-04-02 19:33 UTC, closed without merging