Small fix to WCS compare doc
astropy/astropy pull request #11630
Opened 2021-04-23 10:49 UTC by dstansby

For at least some WCS transformations (e.g. heliographic stonyhurst > heliographic stonyhurst, with different date-obs), the date-obs keyword does change the transformation, so I have tidied up a docstring to reflect this.

2021-04-23 12:41 UTC, pllim commented
I don't understand why CI failed; those should have been patched upstream. Did you not open a PR against the latest `upstream/main`? Just want to make sure these are not new failures.

Also, probably need a rebase anyway to pick up fix for RTD.

2021-04-23 16:52 UTC, mcara requested changes
> For at least some WCS transformations (e.g. heliographic stonyhurst > heliographic stonyhurst, with different date-obs), the date-obs keyword does change the transformation, so I have tidied up a docstring to reflect this.

I think it is more important for the reader to know that `DATE-OBS` will be ignored with this option than to not have this information just because `DATE-OBS` does affect WCS _in some cases_. If anything, I think providing an additional sentence such as "WARNING: However, be aware that `DATE-OBS` may affect a limited number of WCS transformations such as ..."

2021-04-23 18:28 UTC, dstansby commented
Good catch, and my bad for not checking the actual `compare` function. I've updated it to give a bit of a warning now.

2021-04-23 18:36 UTC, mcara reviewed
Instead of `in some cases`, _if possible_, it would be useful to provide a couple of examples like what you have mentioned in the PR. Otherwise it looks good. Thank you!

2021-04-26 21:22 UTC, mcara approved these changes

2021-04-26 21:34 UTC, pllim commented
> it would be useful to provide a couple of examples

@dstansby , do you have plans to provide examples or is it good to go?

2021-04-28 15:47 UTC, pllim commented
Well, I am merging this now, given it is approved and extra example is optional. If you do wish to provide example, feel free to open a follow-up PR. Thanks!

2021-04-28 15:47 UTC, merged