Add milli- prefix to Angstrom unit
astropy/astropy pull request #11788
Opened 2021-05-26 03:12 UTC by byrdie

Added milli- prefix to Angstrom unit, as discussed in Issue #11745.

### Description

This pull request is to address ...

Fixes #<Issue Number>

2021-05-26 13:19 UTC, mhvk approved these changes
Thanks, looks all good. I'll merge once all the tests have passed.

2021-05-26 14:14 UTC, pllim commented
Shouldn't there be a test too?

2021-05-26 14:28 UTC, mhvk commented
The automatic going through all units should be good enough. But I note there is a failure in the doctests, plus a real error because `mÅ` was used in a test to check that it failed.

@byrdie - do you think you'll be able to fix this? If you feel it is too tricky, I can do it for you.

2021-05-26 15:17 UTC, byrdie commented
I will give it a try and let you know if I have any issues.

On Wed, May 26, 2021, 8:28 AM Marten van Kerkwijk ***@***.***>
wrote:

> The automatic going through all units should be good enough. But I note
> there is a failure in the doctests, plus a real error because mÅ was used
> in a test to check that it failed.
>
> @byrdie <https://github.com/byrdie> - do you think you'll be able to fix
> this? If you feel it is too tricky, I can do it for you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/astropy/astropy/pull/11788#issuecomment-848816985>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUTD5JUPTHWSNUVEBD4OETTPUASRANCNFSM45QVZZSQ>
> .
>

2021-05-27 02:40 UTC, dhomeier commented
This works in some unexpected way in that it enables `u.mAngstrom`, `u.milliAA` and `u.milliangstrom` rather than `u.mAA` and `u.milliAngstrom` - the reason being evidently that for `def_unit`
> the first element is the canonical (short) name, and the rest of the elements are aliases.

It might seem more logical then to define it as
```python
def_unit(['AA', 'Angstrom', 'angstrom'], ...
```
but that would break e.g. the expected fits format outputs.
As a kind of alternative workaround you might instead define both prefix versions as aliases for both the short and long form:
```python
    prefixes=[(['m', 'milli'], ['milli', 'm'], 1.e-3)],
```
You will also have to update the matches for test_units:test_suggestions to
```python
    ('ångström', 'Angstrom, angstrom, mAngstrom or mangstrom')
```

2021-05-27 03:25 UTC, byrdie commented
@dhomeier, thanks for explaining that, I had not yet figured out why that test was failing.
I'll add the workaround you posted and update the other test you mentioned.

2021-05-27 11:25 UTC, dhomeier requested changes
If tests are passing after the fix, this is good to go, but I'd let @mhvk have a second look if he agrees with the multiple alias solution.

2021-05-27 11:25 UTC, dhomeier commented on astropy/units/tests/test_units.py
> +            ('ångström', 'Angstrom, angstrom, mAngstrom or mangstrom')
```suggestion
            ('ångström', 'Angstrom, angstrom, mAngstrom or mangstrom'),
```
lost the comma here

2021-05-27 15:52 UTC, mhvk approved these changes
@byrdie - there was still a failure in a doctest (in which `milliangstrom` is now offered - correctly - as an alternative). I went ahead and pushed a change for that to your branch, also squashing your comments in the process. I hope that with this all the tests will pass, because the rest looks all OK. So, I'll approve and merge if tests indeed pass.

Thanks!

2021-05-27 16:00 UTC, dhomeier commented
@mhvk this does raise some concerns that similar problems might pop up downstream if looking for the expected exception. But I don't really see a good alternative if we want to accept `u.mAA` (and I definitely think we should).
One option could be to allow only 'milli' as 'short' prefix, backwards as it may seem
`prefixes=[(['milli'], ['milli', 'm'], 1.e-3)],`
but that would still only get rid of `mAngstrom`, not `mangstrom`, so maybe not much point in it.

2021-05-27 16:16 UTC, dhomeier approved these changes

2021-05-27 16:36 UTC, byrdie commented
@mhvk, thanks for updating the doctest. I didn't know if I was supposed to update the .rst file directly or if there was a docstring in 
 a .py file somewhere that I had to fix.

2021-05-27 16:52 UTC, mhvk commented
@byrdie - yes, I thought this was getting a bit beyond what a supposedly quick PR should do, especially as with those doctests it is often a bit trickier than thought. Anyway, tests pass now and @dhomeier also agrees this is all OK, so I'll merge. Thanks again, and of course other suggestions for making astropy just a little bit better are very welcome!

2021-05-27 16:52 UTC, merged

2021-05-27 16:57 UTC, mhvk commented
p.s. @dhomeier - I agree that the `mAngstrom` is really not all that great, but ended up also agreeing that if `mangstrom` is in there, we should just not perfect be the enemy of good enough. It would have been nicer if the names could just have been swapped, so that `AA` was first.

2021-05-27 17:03 UTC, dhomeier commented
Thanks @byrdie and congrats to completing the first PR into Astropy!

2021-05-27 17:44 UTC, byrdie commented
Thanks @mhvk, @dhomeier and everyone else for your help and allowing me the opportunity to contribute!