Include wcslib errors when parsing fits headers
astropy/astropy pull request #12047
Opened 2021-08-12 09:32 UTC by aragilar

It appears that errors produced when wcslib is scanning fits headers do not get passed up to the user. This adds them to the raised exception, as that appears to be the simplest way to pass them from C to python.

This is the first of the PRs that come from the discussion on slack around trying to read old INT files. This doesn't touch wcslib (only the astropy wrapper).

2021-08-13 02:21 UTC, aragilar commented
Sure, happy to add docs/changelogs if they're desired. Not sure if its on the roadmap at some point, but rewriting the C wcslib wrapper in cython would make it easier to use tools like logging (and make it easier to test and contribute to).

2021-08-14 01:55 UTC, mcara commented
@aragilar Could you, please, provide a link to a file that could be used for testing? Thanks!

2021-08-14 04:39 UTC, aragilar commented
[mgc001_1_B.fit.gz](https://github.com/astropy/astropy/files/6985884/mgc001_1_B.fit.gz) is one of the bad files I have (this is from the MGC survey—Data Central has the originals, and will serve out fixed versions soon). You won't see the actual error (the use of ZPX rather than ZPN) with this PR, that needs some changes to wcslib (the wcslib changes need some cleaning up, I did some hacky stuff to work out why the file was invalid).

2021-08-18 05:36 UTC, mcara commented on astropy/wcs/src/pyutil.c
> +  wcsperr(wcs, "");
```suggestion
  wcsperr(wcs, NULL);
```
From the [docs](https://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/wcs_8h.html#a8fe5dcd9927240dc0348b850ee662367):
> prefix | If non-NULL, each output line will be prefixed with this string.

2021-08-18 05:37 UTC, mcara commented on astropy/wcs/src/pyutil.c
> +      "Memory allocation error (internal details %s)",
```suggestion
      "Memory allocation error:\n%s",
```

2021-08-18 05:37 UTC, mcara commented on astropy/wcs/src/pyutil.c
> +      "Internal error in wcslib header parser (internal details %s)",
```suggestion
      "Internal error in wcslib header parser:\n %s",
```

2021-08-18 05:39 UTC, mcara requested changes
Seems reasonable. I added a couple of minor suggestions that surrounding the original error message with parenthesis does not look clean to me. For example, currently the error message looks like this:
```
ValueError: Internal error in wcslib header parser (internal details EQUINOX = '2000.   '           / Equinox of coordinates
  Rejected (1), a floating-point value was expected.
RADECSYS= 'FK5     '           / mean place new (after the 1976 IAU) system
  Rejected (2), the RADECSYS keyword is deprecated, use RADESYSa.
)
```
I think something like this:
```
ValueError: Internal error in wcslib header parser:
EQUINOX = '2000.   '           / Equinox of coordinates
  Rejected (1), a floating-point value was expected.
RADECSYS= 'FK5     '           / mean place new (after the 1976 IAU) system
  Rejected (2), the RADECSYS keyword is deprecated, use RADESYSa.
```
is somewhat better looking.

2021-09-04 04:34 UTC, aragilar commented
@mcara I've added your suggestions around the text, I agree they look better.

2021-09-07 03:14 UTC, mcara approved these changes
LGTM. Thanks!

2021-09-07 03:14 UTC, merged