Make indexing in models more robust
astropy/astropy pull request #12561
Opened 2021-12-06 10:20 UTC by krachyon

### Description
Currently integer-indexing a model is only possible with built-in python integers, `numpy` ints don't work e.g.:
```python
my_model[np.int64(0)] 
-> TypeError('index must be integer, slice, or model name string')
```
This makes the type check more general to allow anything that fits into the duck-type category "whole number".

Also, comparing against `str` directly is a bit more clear and should save a few CPU-cycles.

edit: I didn't really touch the changelog or anything because this seems a bit too small to mention there...

2021-12-06 11:31 UTC, Cadair commented
Hey @krachyon Thanks for the PR the changes look good. Would you be able to add a bugfix changelog entry, following the docs here: https://docs.astropy.org/en/latest/development/workflow/development_workflow.html?highlight=changelog#add-a-changelog-entry

2021-12-06 14:08 UTC, pllim commented
cc @WilliamJamieson (cannot seem to add you as reviewer)

2021-12-06 15:26 UTC, WilliamJamieson requested changes
Looks good.

Can you add a unit test for model indexing using the different numpy integer types?

2021-12-07 18:51 UTC, WilliamJamieson approved these changes
Looks good. Thanks for the unit tests.

2021-12-07 19:15 UTC, pllim commented on astropy/modeling/tests/test_core.py
> +    assert compound['Mimi'] == airy
I don't know what Jona and Mimi is but they don't look related to modeling. Can we change these to something more generic like "Model1" and "Model2" or something like that?

2021-12-07 19:16 UTC, pllim commented on docs/changes/modeling/12561.bugfix.rst
> +(like `numpy.int64`) instead of just `int`
```suggestion
Indexing on models can now be used with all types of integers
(like ``numpy.int64``) instead of just ``int``.
```

2021-12-18 12:24 UTC, nden commented on astropy/modeling/core.py
> +        if isinstance(index, numbers.Integral):
`numbers.Integral` will also allow boolean indexes though this should not be a stopper for the PR.

2021-12-19 12:04 UTC, nden commented
@krachyon COul dyou rebase to get rid of the merge commit? And squash commits?

2022-03-09 00:11 UTC, merged

2022-03-09 00:13 UTC, pllim commented
@WilliamJamieson , if you really want this backported, please do a manual backport. Otherwise, please change the milestone. Thanks!