Add a tickable gridline to a WCSAxes plot
astropy/astropy pull request #13829
Opened 2022-10-13 02:03 UTC by ayshih

For WCSAxes plot, gridlines are normally given ticks and/or labels only where they intersect with the outside rectangular frame of the plot.  (If using `EllipticalFrame` instead of `RectangularFrame`, the situation is a bit different.)  However, having gridline labels within the plot is at times desirable, and downright necessary when the gridlines do not intersect with the outside frame of the plot at all.

This PR makes it possible to add a tickable gridline to a WCSAxes plot.  For example, one can specify a particular gridline of constant latitude.  That gridline can then have ticks and labels added to it for every line of longitude that intersects with it, even in the interior of the plot.  (This behavior is essentially a generalization of the major and minor axes of `EllipticalFrame`.)

Here's an example.  Currently, the final plot on https://docs.astropy.org/en/stable/visualization/wcsaxes/index.html is:
![download (64)](https://user-images.githubusercontent.com/991759/195480346-c9e4cce1-9ebf-42d4-88c6-1fed8dbb078d.png)
With this PR, one can add:
```python
from astropy.coordinates import Angle

overlay['ra'].add_tickable_gridline('m', Angle('266d15m'))
overlay['dec'].add_tickable_gridline('n', Angle('-29d15m'))

overlay['ra'].set_ticks_position('n')
overlay['ra'].set_ticks(color='red')
overlay['ra'].set_ticklabel_position('n')
overlay['ra'].set_ticklabel(color='red', size=6)
overlay['ra'].set_axislabel_position('r')
overlay['ra'].set_axislabel('Right Ascension (J2000)', color='red')

overlay['dec'].set_ticks_position('m')
overlay['dec'].set_ticks(color='magenta')
overlay['dec'].set_ticklabel_position('m')
overlay['dec'].set_ticklabel(color='magenta', size=6)
overlay['dec'].set_axislabel_position('t')
overlay['dec'].set_axislabel('Declination (J2000)', color='magenta')

ax.coords[0].set_ticks_position('b')
ax.coords[1].set_ticks_position('l')
```
to now get:
![download (67)](https://user-images.githubusercontent.com/991759/195481314-515923dd-797e-41f6-a982-e76757b71278.png)
Note that the tick labels are in the interior plot along the not-drawn tickable gridlines of constant RA and constant declination, respectively.

---

As a wackier example to showcase the possibilities:
![download (66)](https://user-images.githubusercontent.com/991759/195480779-fc68eab9-9d32-445b-ac0f-55d1e43f8f09.png)

2022-10-13 14:56 UTC, Cadair commented
This looks super cool, and is a really elegant solution. Let me know if there's anything I can do to contribute or help it along.

2022-10-13 15:55 UTC, astrofrog commented
This is amazing, thank you @ayshih! Not to put pressure or anything but it would be great if we could include this in the upcoming release! :smile: 

API-wise, I need to think about it, but maybe a question in the mean time - does this work properly when there are e.g. 3 world coordinates instead of two? (just in case it helps us figure out if there is a better API - as then there aren't just two 'complementary' coordinates).

2022-10-13 16:44 UTC, ayshih commented
> does this work properly when there are e.g. 3 world coordinates instead of two?

I don't know because I haven't tried it yet. =)  However, if it doesn't work, I suspect that would mean some other part of the grid code *already* doesn't work, because I'm specifying and checking the gridline the same way.

2022-10-14 03:27 UTC, ayshih commented
As an example for how tickable gridlines overcome some of the limitations of `EllipticalFrame`, I start with the [`EllipticalFrame` example in the docs](https://docs.astropy.org/en/stable/visualization/wcsaxes/custom_frames.html):
![download (68)](https://user-images.githubusercontent.com/991759/195754356-37d853ef-a0a1-4711-bcf0-509a3639eafe.png)
This use case is where `EllipticalFrame` shines.  However, if you try to crop out part of the bottom of the all-sky image, this is what you get:
![download (69)](https://user-images.githubusercontent.com/991759/195754369-d641b9aa-21b9-416a-b627-11bd85ce337d.png)
The elliptical frame no longer coincides with the bounds of the coordinate system.  Consequently, most of the latitude lines do not intersect with the frame, and thus most latitude tick labels are missing.  The longitude tick labels are now positioned at ~30 deg latitude (the midpoint of the y range) instead of at the equator.  (Look for the black ticks on the white longitude lines.)

As an alternative, here's how one would use `RectangularFrame` and added tickable gridlines to get close the desired labeling.  (For fun, I have given the tickable gridlines multi-character names to show how that is possible.)  
```python
from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename
from matplotlib import patheffects
import matplotlib.pyplot as plt

filename = get_pkg_data_filename('allsky/allsky_rosat.fits')
hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)
ax = plt.subplot(projection=wcs)

path_effects=[patheffects.withStroke(linewidth=3, foreground='black')]
ax.coords.grid(color='white')
ax.coords['glon'].set_ticklabel(color='white', path_effects=path_effects)

im = ax.imshow(hdu.data, vmin=0., vmax=300., origin='lower')

ax.set_ylim(99.5, 239.5)

ax.coords[0].set_ticks(spacing=30*u.deg)

ax.coords[1].add_tickable_gridline('equator', 0*u.deg)
ax.coords[0].set_ticklabel_position(('equator',))
ax.coords[0].set_ticks_position(('equator',))

ax.coords[0].add_tickable_gridline('left', 180*u.deg)
ax.coords[0].add_tickable_gridline('right', -180*u.deg)
ax.coords[1].set_ticklabel_position(('left', 'right'))
ax.coords[1].set_ticklabel(color='magenta')
```
![download (70)](https://user-images.githubusercontent.com/991759/195755179-4014c17c-ebba-4c16-9c71-218cddac056f.png)
It's clear that there are some issues to resolve – what in the world is going on with the label for 180-deg longitude? – but most of the latitude and longitude labels are where desired.

2022-10-27 08:33 UTC, astrofrog commented
Since there are many unresolved TODOs above, I think we will not get this in in time for v5.2, so I am re-milestoning. However, @ayshih if you think you can resolve all this by tomorrow let me know and I can change the milestone back.

2022-10-28 05:41 UTC, ayshih commented
Okay, ready for review!

2022-10-28 07:46 UTC, astrofrog requested changes
@ayshih - thank you for finishing this up so fast! This generally looks good to go but I have noticed an issue in the example:

![overlaying_coordinate_systems-4](https://user-images.githubusercontent.com/314716/198532590-4cee742a-e952-40ba-8674-1003d00b4907.svg)

Should the ticks not be adjacent and perpendicular to one of the grid lines? Is this just a matter of fixing the 'constant' coordinate in both cases?

Once this is resolved, we can merge in time for v5.2! 😄

2022-10-28 07:48 UTC, astrofrog commented
I realise that it might have been deliberate to show the ticks floating not actually along a grid line, but I wonder whether it would make more sense as a documentation example to show a case where it is shown along one of the existing grid lines? Maybe also make the grid line colors match the ticks?

2022-10-28 08:18 UTC, astrofrog commented
Alternatively can we make the tickable grid line visible for this example?

2022-10-28 11:35 UTC, ayshih commented
It was deliberate from a testing perspective, but it does look silly in the documentation given that placing ticks on an invisible gridline is a rather niche use case.  I'll modify the examples.

2022-10-28 14:25 UTC, astrofrog approved these changes
Looks great, thank you!

2022-10-28 14:25 UTC, merged

2022-10-28 14:29 UTC, Cadair commented
I think this should probably get a what's new?

2022-10-28 15:35 UTC, pllim commented
Who is going to write it?

2022-10-28 16:02 UTC, astrofrog commented
@ayshih would you be able to do this?

2022-10-28 16:33 UTC, ayshih commented
I'd be happy to write it, but I'll warn that I probably won't be able to get to it today.

2022-10-28 19:26 UTC, pllim commented
Hard to track a merged PR so I opened https://github.com/astropy/astropy/issues/13932 for the What's New. Thanks!