Deprecate getting/setting pix on WCSAxes Spine
astropy/astropy pull request #13989
Opened 2022-11-06 13:20 UTC by dstansby

### Description
(this is a revival of https://github.com/astropy/astropy/pull/12621)

When using Matplotlib, it is generally only safe to calculate pixel coordinates of artists at draw time, as that is when the figure DPI is set in stone. Calculating the pixel coordinates before drawing can lead to issues like https://github.com/astropy/astropy/issues/12568.

This PR fixes this issue for `WCSAxes` `Spine`s by ensuring that pixel calculations are done at draw time. It also deprecates getting and setting pixel coordinates.

This pull request is to partly address https://github.com/astropy/astropy/issues/12568. Before that issue can be fully resolved I think there is also a fix required on the Matplotlib side.

Fixes #<Issue Number>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

2022-11-27 11:07 UTC, dstansby commented
Test failures look real.

2022-12-02 15:26 UTC, pllim commented
Hello!

> Test failures look real.

Does this mean that we cannot deprecate? Or does it mean that the tests or some code need update?

Do you need assistance?

2022-12-02 17:34 UTC, dstansby commented
Needs an update, I should be able to look into this myself when I have time.

2023-02-03 19:11 UTC, larrybradley requested changes

2023-02-03 19:11 UTC, larrybradley commented on astropy/visualization/wcsaxes/frame.py
> +            self._data = value
I think this line can be removed.  It's not a duplicate of line 149.

2023-02-03 19:11 UTC, larrybradley commented on astropy/visualization/wcsaxes/frame.py
> +            self._data = None
Same here.

2023-03-15 17:48 UTC, dstansby commented
👍 done

2023-03-15 17:55 UTC, pllim commented
@larrybradley , please re-review. Thanks!

2023-03-29 20:42 UTC, astrofrog reviewed
Looks good to me! But could we include an image test for the bugfix, even if it needs updating once the remaining issues are resolved in follow-up PRs/matplotlib?

2023-03-31 10:33 UTC, astrofrog approved these changes
This looks good to me!

I went down a rabbit hole trying to set up a test for this because it does not happen with PNG output, but does with e.g. PDF. So I have been working on extending pytest-mpl to be able to compare PDF output (see https://github.com/matplotlib/pytest-mpl/pull/194). So let's plan to add a regression test in future once the pytest-mpl changes are in a release.

2023-03-31 10:33 UTC, astrofrog commented
(I have rebased this to make sure the test failures were unrelated)

2023-03-31 13:03 UTC, pllim commented
@larrybradley , do you want to re-review since you requested changes?

2023-03-31 13:44 UTC, larrybradley approved these changes
LGTM.  I just pushed a small change to remove an unnecessary line.

2023-03-31 14:22 UTC, merged

2023-03-31 14:23 UTC, pllim commented
Thanks, all!