Added a feature which will allow the user to control space b/w value and unit [ci skip]
astropy/astropy pull request #14231
Opened 2022-12-24 18:48 UTC by Telomelonia

### Description

I added a boolean feature `oldstyle` in `to_string()`, giving flexibility to the user to have a space between value and unit.
By default, space is given in between whenever its possible.
**NOTE**-For some units like 34'20'' or 11<sup>h</sup>22<sup>m</sup> no space should be added whether the feature is set to `True` or `False`.
```
oldstyle : bool, optional
            If `False`, include a space between value and unit. If `True`,
            no space is included. Doesn't work with 'latex' or 'unicode'
            format. By default a space is generated.
```

### TODOs
- [x] Adding the feature as a boolean keyword
- [x] Updating the Docstring
- [ ] Add a changelog

This pull request is to address ...

Fixes #7455 

### Testing
![image](https://user-images.githubusercontent.com/88445101/209447902-0bc01e9b-ccfa-493b-a10e-87fe21940128.png)
![image](https://user-images.githubusercontent.com/88445101/209447953-fb6e49cf-d39c-48e1-ae29-3ece94ae57fe.png)

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label. Codestyle issues can be fixed by the [bot](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit).
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

2022-12-25 22:23 UTC, pllim commented
The tests need updating. A new test to use the alternate option is also necessary.

Also a change log is necessary (as you have noted in your checklist).

Thanks!

2022-12-28 00:55 UTC, mhvk requested changes
Thanks for the PR, but I wonder why this is needed? Most journals insist that a space is used between a number and the unit. Also, while for simple units this might make sense, it does not generalize to composite units (which have spaces in between them).

Overall, my tendency would be to leave this for people to sort for themselves if they want it; generally `.to_string(...).replace(' ', '')` will be all that's needed.

So, not in favour; marking as "request changes" since if we were to go for adding this option, it definitely should have a different name.

2022-12-28 00:55 UTC, mhvk commented on astropy/coordinates/angles.py
> +        oldstyle=False
This name is not very informative. `Quantity.to_string`, which `Angle` as a `Quantity` subclass should ideally follow, has `subfmt`, which I guess one could use instead.

2022-12-28 01:00 UTC, mhvk commented
Oops, I'm so sorry, I hadn't even realized that the issue here is to *fix* that angles do not have spaces between the number and the unit. Very silly of me; I should have read the issue.

Now having done so, I agree with the comments there that the default should be to have the space, with the only exception being when one of the special symbols is used. My tendency would be not to even have an option for this.

Anyway, now *in favour* as long as we change the default!

2022-12-28 01:04 UTC, mhvk reviewed
A few more thoughts.

2022-12-28 01:04 UTC, mhvk commented on astropy/coordinates/angles.py
> +                # Add a space if no format(i.e unicode or latex) is given
I wonder if the whole `else` clause could simply leave it to `Quantity.to_string()` via
```
return super().to_string(unit=unit, precision=precision, format=format)
```

2022-12-28 01:04 UTC, mhvk commented on docs/changes/coordinates/14231.feature.rst
> +The ``oldstyle`` option is now available for ``to_string``.
Maybe for once decisions have been made, but I think this should be an `api` that states that spaces are now inserted before units in `Angle.to_string()`.

2023-02-08 12:44 UTC, Telomelonia commented
@pllim 
I have a problem regarding the pre-commit.ci check. Apart from that all is good to go

2023-02-08 13:21 UTC, pllim commented
pre-commit.ci autofix

2023-02-08 13:30 UTC, pllim reviewed
A test need to be added with `oldstyle=True` to ensure it works as intended.

Please renamed the change log fragment file from `14231.feature.rst` to `14231.api.rst` as suggested by reviewer. Change log text also need to elaborate what this ``oldstyle`` actually does and why it is needed now.

Needs to squash all commits into one before this is ready for merge too. To do that, please remember to pull in pre-commit autofix commit from GitHub back to your local checkout first. Feel free to ask if you are unsure how to do this part.

2023-02-08 13:30 UTC, pllim commented on astropy/coordinates/angles.py
> +            no space is included. Doesn't work with 'latex' or 'unicode'
```suggestion
            no space is included. This option does not work with 'latex' or 'unicode'
```

2023-02-08 16:53 UTC, eerovaher commented
> I have a problem regarding the pre-commit.ci check. Apart from that all is good to go

`pre-commit` can fix most (if not all) issues it highlights, see https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit

2023-02-09 12:17 UTC, Telomelonia commented
pre-commit.ci autofix

2023-02-09 13:45 UTC, pllim commented
Re: https://github.com/astropy/astropy/pull/14231#issuecomment-1422651982

@mhvk , I think that is a discussion for astropy-dev mailing list and/or dev telecon. I am going to turn this PR into draft until this discussion is resolved.

2023-02-09 18:50 UTC, mhvk commented
Let's just ping the coordinate team - @eerovaher, @StuartLittlefair, @adrn, @eteq - on whether to make a space between a number and the unit the standard case (as it is for `Quantity`), or whether it is important to allow users to keep the "old style" where, for `Angle` only, the space was omitted (likely by mistake). I feel this is a quite clear case of only one correct way, and that effectively this is a bug fix, with little or no impact to anyone since it affects only how angles are shown in string form. So, I'm in favour of just changing, without an option to get the old behavor back (which, after all is just a `f"{angle.value}{angle.unit}"` away, probably easier to discover than a keyword argument!).

2023-02-10 12:48 UTC, StuartLittlefair commented
Just to sat that in response to @mhvk's ping, I have no strong opinion on this. The only real issue I can anticipate is if third-parties had based their unit tests on the string output from angles, in which case I don't have much sympathy...

2023-02-13 19:36 UTC, Telomelonia commented
I thinking of making another PR to address this issue as just a bug where a space is required in the result in between value and unit.

2023-02-13 20:19 UTC, mhvk commented
@Telomelonia - it might indeed be good to have 2 PRs to compare, though it also is fine to work with this one, Thanks for persisting!!!

2023-04-19 03:13 UTC, closed without merging