Bug fix of no space in the result of to_string.
astropy/astropy pull request #14379
Opened 2023-02-13 20:28 UTC by Telomelonia

### Description

As mentioned in the issue, in the result of the to_string() function, there is no space between value and unit.So, I added a space between value and unit.

This pull request is to address ...

Fixes #7455

2023-02-13 20:54 UTC, pllim commented on docs/changes/coordinates/14379.bugfix.rst
> +The bug is fixed in ``to_string``.
You would have to elaborate what "the bug" is here. This will be part of the change log for the whole package.

2023-02-14 18:22 UTC, mhvk commented on docs/changes/coordinates/14379.bugfix.rst
> +In result of ``to_string``, there is no space between value and unit.
Sorry, realize my suggestion for the changelog message was actually wrong -- now edited above to give something that's hopefully correct!

2023-02-14 20:19 UTC, eerovaher requested changes
With the changes this pull request is proposing the following works as it should:
```python
>>> from astropy.coordinates import Angle
>>> Angle(5, unit="rad").to_string()
'5 rad'
```
But the following still produce a string without a space (it would be good to add a unit test analogous to one of these):
```python
>>> Angle(5, unit="rad").to_string(format="unicode")
'5rad'
>>> Angle(5, unit="rad").to_string(format="generic")
'5rad'
```
It would seem that a space should not be added between the value and the unit if the format is `"latex"` or `"latex_inline"`, or if the output is sexagesimal.

2023-02-14 21:13 UTC, mhvk commented
Oops, indeed, this is more of a partial fix than I had realized! I think in principle there should be a space also for `latex`, etc. In #14231, I had [suggested](https://github.com/astropy/astropy/pull/14231/files#r1057999266) to use `super()` for the non-sexagesimal case, but a quick try caused more breakage than I had thought would be the case. Also `Quantity.to_string()` does not support `unicode` (see new issue #14386) and arguably does `latex` wrong in typesetting the degree symbol with a space in between it and the value (new issue #14385).

One option here may be to just keep it simple and focus on the generic format only -- i.e., only update this PR to also allow `format='generic'`.

2023-02-15 18:35 UTC, Telomelonia commented on astropy/coordinates/tests/test_angles.py
> +        ([np.nan, 1, 0] * u.rad, "[nan 1 rad 0 rad]", "[nan, 1., 0.] rad"),
Yeah, it is not looking good, but I cannot think of how to sort it out.

2023-02-15 18:43 UTC, Telomelonia commented
> Oops, indeed, this is more of a partial fix than I had realized! I think in principle there should be a space also for `latex`, etc. In #14231, I had [suggested](https://github.com/astropy/astropy/pull/14231/files#r1057999266) to use `super()` for the non-sexagesimal case, but a quick try caused more breakage than I had thought would be the case. Also `Quantity.to_string()` does not support `unicode` (see new issue #14386) and arguably does `latex` wrong in typesetting the degree symbol with a space in between it and the value (new issue #14385).
> 
> One option here may be to just keep it simple and focus on the generic format only -- i.e., only update this PR to also allow `format='generic'`.

I think one way is to include every format possible where space is required, since few units don't require space like `32'48''`  so there is too much if and else ... another possible way is to take the output from the function and check whether space should be given or not and if space is required then add 1 space else pass
The another task is to insert the space in the Latex part

2023-02-15 19:01 UTC, mhvk commented
My sense is still that apart from sexagesimal, this should all be handled by `Quantity.to_string()`. It may not be that tricky if we require that the `latex` and `unicode` entries for unit formats include whether a space is needed -- may need to edit things like Å and Ω -- or simply special-case the few that do not.

My sense, though, is not to let that stand in the way of doing the smaller change here, which solves things mostly.

2023-04-18 19:37 UTC, mhvk commented
@Telomelonia - I squashed your commits and added an extra one that also adds a space for other formats. I think this way it is ready to go in!

@eerovaher - would you mind having another look? I think your comment is now addressed.

2023-04-18 19:38 UTC, mhvk approved these changes

2023-04-18 20:34 UTC, mhvk commented
Hopefully now got the `visualization.wcsaxis` bugs - should have tested locally with `matplotlib` installed...

2023-04-18 20:38 UTC, pllim commented
Are the "TODO"s in original post above still relevant?

2023-04-18 20:47 UTC, mhvk commented
@pllim - I think they're basically done with my additional commit, so I ticked them.

2023-04-19 00:15 UTC, larrybradley approved these changes

2023-04-19 03:13 UTC, merged

2023-04-19 03:13 UTC, pllim commented
Thanks, all!

2023-04-25 05:05 UTC, Telomelonia commented
> @Telomelonia - I squashed your commits and added an extra one that also adds a space for other formats. I think this way it is ready to go in!
> 
Thank you all for assisting me