Add deprecation warning to NDArithmetic.
astropy/astropy pull request #14414
Opened 2023-02-18 11:32 UTC by DanRyanIrish

### Description
Add deprecation warning to NDArithmetic.  This alerts users to change of meaning of propagate_uncertainties=False for v6.0. At that stage this will become equivalent to propagate_uncertainties=None and current first-found behaviour triggered by propagate_uncertainties=False will be dropped unless users request it be kept through another API.

Fixes #14404

2023-02-18 12:51 UTC, DanRyanIrish commented
ping @mwcraig @bmorris3

2023-02-18 13:11 UTC, DanRyanIrish commented
I also opened a PR (#14415) to remove the deprecation warning and trigger the new behaviour for 6.0.

2023-02-20 14:44 UTC, mwcraig requested changes
Thanks for opening this @DanRyanIrish -- like I said in #14404 I'm not sure what the original motivation for this API was, but it doesn't make much sense today.

Could you please add a test that uses `propagate_uncertainties=False` that checks that the warning is raised and that the resulting uncertainty is what is expected under the old API (`"first_found"`)?

2023-02-20 14:53 UTC, mwcraig commented
@DanRyanIrish -- can you please also add a changelog entry and a brief mention of the change in the documentation (or at least in the docstring)?

2023-04-18 13:21 UTC, pllim commented
There is a conflict now. @DanRyanIrish , are you still interested to wrap this up for v5.3? Its feature freeze is in 3 days (2023-04-21).

2023-04-22 21:02 UTC, saimn commented
Should this be delayed to v6.0 ? Or anyone has time to finalize it (quickly :pray: ) ?

2023-05-06 15:09 UTC, pllim commented
Too late for v5.3 now. Re-milestoning.

2023-08-19 15:04 UTC, pllim commented
There is a conflict that needs to be resolved.

And you need to rebase to reset the timer. Otherwise, the bot is going to mark this as stale again. Thanks!

2023-08-19 15:12 UTC, mwcraig commented
Thanks for the reminder @pllim! I have rebased this @DanRyanIrish.

2024-02-17 05:34 UTC, closed without merging