Improve toctree on coordinates landing page
astropy/astropy pull request #14563
Opened 2023-03-22 14:24 UTC by dstansby

Currently the table of contents for the coordinates landing page is hard to parse:

![Screenshot 2023-03-22 at 14 23 55](https://user-images.githubusercontent.com/6197628/226934434-a0ad5f7a-f35e-423a-a534-0fed7df349f5.png)

This PR removes the "Examples" section headings, making for a slightly nicer and easier to read table of contents:
![Screenshot 2023-03-22 at 14 24 40](https://user-images.githubusercontent.com/6197628/226934672-4023ed95-c2a0-47ec-bc5a-7dba3fab3021.png)

2023-03-22 16:36 UTC, eerovaher requested changes
I would agree this is an improvement, and there are sub-packages that don't have any "Examples" section headings already, e.g. [`constants`](https://docs.astropy.org/en/stable/constants/index.html) or [`table`](https://docs.astropy.org/en/stable/table/index.html). Ideally we should try to make all the landing pages consistent by making analogous changes to all the sub-packages, but I'm not sure if it's best to do that in a single pull request or not.

I will point out that some of the source code for the `coordinates` landing page is in a separate file: https://github.com/astropy/astropy/blob/d3b5af50f6c1cfa14da0799c8835426d6db1a39e/docs/coordinates/index.rst#L540
That file should also be cleaned up: https://github.com/astropy/astropy/blob/d3b5af50f6c1cfa14da0799c8835426d6db1a39e/docs/coordinates/performance.inc.rst#L26-L27

2023-04-18 13:12 UTC, pllim commented
@dstansby , are you able to address review comments by feature freeze on 2023-04-21? Thanks!

2023-04-18 14:19 UTC, dstansby commented
Sorry, I won't have a chance to come back to this in the near future, feel free to close or someone else is welcome to push to my branch.

2023-04-18 14:27 UTC, pllim commented
@eerovaher , are you interested to take over or should we just close this without merge?

2023-04-18 19:05 UTC, mhvk approved these changes
Yes, good (and fine to do it subpackage by subpackage)

2023-04-18 20:20 UTC, merged

2023-04-18 20:21 UTC, pllim commented
Thanks, all!