#14840 Issue: Address Ruff Rule C408 in astropy/io Sub-package
astropy/astropy pull request #14841
Opened 2023-05-17 23:10 UTC by Mubin17

### Description

Refactored the code in the astropy/io sub-package to address the Ruff rule C408 violation. Replaced unnecessary dict calls with corresponding literals.
This pull request is to address Issue #14840

Fixes #<14840>

2023-05-18 01:18 UTC, nstarman commented
Thanks @Mubin17! This all looks very good. And it's wise to tackle these corrections on a sub package basis.
Side note, we recommend installing pre-commit on your computer (see https://pre-commit.com/#usage), which should automatically apply black and ensure that the pre-commit CI always passes.
Also, now that C408 is enforced, let's keep it enforced! 
In ``.ruff.toml``, if you could remove C408 from the ignore list (https://github.com/astropy/astropy/blob/12b01d7cab1b9f4884205bd9f71dc971d4529d5d/.ruff.toml#L32)
and copy it to the per-file-ignore list (at https://github.com/astropy/astropy/blob/12b01d7cab1b9f4884205bd9f71dc971d4529d5d/.ruff.toml#L287-L309), except for `astropy/io` of course, that would be great! Also, fixing C408 in the next sub package is as easy as removing it from the relevant per-file-ignore list!

2023-05-18 02:50 UTC, nstarman commented
@Mubin17, I found a configuration error in the ``.ruff.toml`` and am pushing a fix as part of #14843. Maybe hold off on editing ``.ruff.toml`` until that PR is in.

2023-05-18 09:40 UTC, matteobachetti commented
Modifications to `io.misc` are trivial, no issues there

2023-05-19 00:11 UTC, pllim requested changes
Please do not introduce merge commit in your PR commits. You need to _rebase_ instead. Thanks!

2023-05-19 01:38 UTC, pllim commented
@Mubin17 , please try the following:

1. First make a backup branch, in case things go wrong.
2. `git fetch upstream main`
3. Then on this branch, do `git rebase upstream/main`
4. If there is any conflict, it will guide you through conflict resolution, so read the prompts.
5. If no conflicts or after they are resolved, do a `git log`. You should see only your commits without merge commit in between.
6. If you are still unsure, do a `git diff HEAD~2` (since right now you have 2 real commits) and you should see only your changes.

When you are confident it is correctly done, do `git push origin Mubin17/14840Issue -f`

Good luck!

2023-05-19 02:27 UTC, Mubin17 commented
@pllim Thanks for the help!

2023-05-23 10:58 UTC, Mubin17 commented
> I notice this pull request has two commits: the first fixes the rule violations in `astropy.io`, the second edits `.ruff.toml`. [If `pre-commit` is set up](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit) then it would be simpler to first edit `.ruff.toml` and then to make the commit without manually editing any other files. If Ruff can autofix the rule (it can autofix C408) then the Ruff `pre-commit` hook automatically fixes the rule violations and the Black hook automatically fixes any code style issues (if any are needed).

Thanks @eerovaher for the suggestion! I feel like editing the .ruff.toml file first and then committing the changes without manual file editing sounds like a much smoother workflow. I'll definitely keep this in mind when I tackle Ruff rule-C408 in other Astropy sub-packages.

Just a quick question: Do you think the current pull request is ready to be merged, or if there are any additional changes or considerations you would like me to address?

2023-05-23 17:02 UTC, eerovaher commented
I suggest squashing the commits.

I have an additional recommendation about commit messages. GitHub knows which commits belong to which pull requests regardless of the commit messages, and [linking pull requests to issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) does not depend on the commit messages either. Including GitHub issues in commit messages therefore provides little benefit to GitHub users. Furthermore, issues and pull requests are a GitHub feature, not a Git feature, so including issue numbers in commit messages usually doesn't help anyone using Git either, although there are some exceptions to this. Replacing `dict()` calls with dictionary comprehensions does not depend on GitHub at all, so this is not one of the exceptions where adding an issue number to the commit message would be helpful.

2023-05-24 13:56 UTC, Mubin17 commented
@eerovaher I've squashed all the commits into one and have updated the commit messages to an appropriate one.

2023-05-24 14:48 UTC, nstarman approved these changes
Thanks @Mubin17. This all looks very straightforward and it's nice there's an autofix available.

As reference for anyone looking at this: [Rule C408](https://beta.ruff.rs/docs/rules/unnecessary-collection-call/) has 2 benefits:

1. it's faster because there's no global namespace lookup.
2. it's safer because callables like `dict` can be rebound, but language-level syntax like `{}` cannot, so `{}` unambiguously means a dict has been created.

2023-05-24 15:33 UTC, eerovaher requested changes
Currently C408 is being removed from the global ignore list and is added to the ignore lists of individual sub-packages, except for `astropy/io` in which the violations are fixed. However, there are subpackages in `astropy` that already comply with C408. I have highlighted `astropy/config`, but there are more. C408 should only be added to the ignore lists of the sub-packages where it is needed.

2023-05-24 15:33 UTC, eerovaher commented on .ruff.toml
> +"astropy/config/*" = ["C408"]
`astropy/config` already complies with C408, so Ruff shouldn't be told to ignore this rule there.

2023-05-25 15:29 UTC, Mubin17 commented
@eerovaher I have made the requested changes, can you please review them thanks

2023-05-25 17:34 UTC, eerovaher approved these changes

2023-05-28 14:48 UTC, Mubin17 commented
@nstarman Does this PR need any additional changes? If not can it be merged?

2023-05-28 18:34 UTC, nstarman commented
I think we’re good to go. IMO this is a clear and positive change. Thanks @Mubin17 for the PR!

2023-05-28 18:35 UTC, merged