Use chained exceptions instead of combining them
astropy/astropy pull request #14866
Opened 2023-05-24 20:16 UTC by CaioCoutinhoP

### Description

I chose some instances to make the change. After running the grep -r 'except .*Error as' astropy/io/ and grep -r 'except Exception as' astropy/io , I discovered these specific instances that need to be modified.

2023-05-24 23:41 UTC, pllim commented on astropy/io/fits/fitsrec.py
> +            )from exc
```suggestion
            ) from exc
```

2023-05-25 00:50 UTC, pllim commented
Thanks!

pre-commit.ci autofix

2023-05-25 15:50 UTC, taldcroft commented
@CaioCoutinhoP - I am OK with changing to chained exceptions, with the important point that you **do not change the exception message at all**. For instance in the ECSV error message it is critical to see the reason for the problem in the final exception message. I made a malformed ECSV file and tried to read, and it gives this helpful message:
```
File ~/git/astropy/astropy/io/ascii/ecsv.py:373, in EcsvOutputter._convert_vals(self, cols)
    368     raise ValueError(
    369         f"column {col.name!r} failed to convert: "
    370         "column value is not valid JSON"
    371     )
    372 except Exception as exc:
--> 373     raise ValueError(f"column {col.name!r} failed to convert: {exc}")

ValueError: column 'b' failed to convert: could not convert string to float: 'hello'
```

With your changes, the `could not convert string to float: 'hello'` would be buried several pages up in the traceback, making it difficult for users to see what went wrong.

2023-08-02 18:16 UTC, taldcroft requested changes
@CaioCoutinhoP - there are still a few cases where the exception message is being changed. If you revert those then this PR can likely get merged.

2023-11-23 05:35 UTC, closed without merging