Fix Implicitly Concatenated String Literals (Ruff ISC001)
astropy/astropy pull request #14911
Opened 2023-06-03 15:21 UTC by Maia-jp

This pull request fixes a series of Implicitly Concatenated String Literals issues (ISC001).

The following files and lines have been addressed:
- astropy/convolution/tests/test_kernel_class.py:226:39
- astropy/convolution/tests/test_kernel_class.py:241:39
- astropy/convolution/tests/test_kernel_class.py:378:19
- astropy/convolution/tests/test_kernel_class.py:396:19
- astropy/coordinates/tests/test_iau_fullstack.py:206:15
- astropy/io/ascii/daophot.py:32:9
- astropy/io/ascii/daophot.py:32:17
- astropy/io/ascii/tests/test_ipac_definitions.py:101:15
- astropy/io/fits/hdu/image.py:275:25
- astropy/io/fits/tests/test_fitstime.py:392:19
- astropy/table/tests/test_column.py:762:15
- astropy/table/tests/test_column.py:775:15
- astropy/table/tests/test_column.py:815:15
- astropy/table/tests/test_table.py:2237:19
- astropy/table/tests/test_table.py:2672:15
- astropy/timeseries/periodograms/lombscargle_multiband/core.py:236:38
- astropy/units/tests/test_logarithmic.py:209:13
- astropy/units/tests/test_logarithmic.py:211:21
- 

The changes involve explicitly concatenating the string literals

2023-06-04 18:05 UTC, nstarman requested changes
I think these are all very uncontroversial. Most probably arose during the `black` PR. A nice cleanup!

@Maia-jp, please see the "Editing Ruff configuration" section of https://github.com/astropy/astropy/issues/14818#issue-1707345588. We want to ensure that this rule continues to be enforced.

2023-06-13 18:17 UTC, eerovaher reviewed
The changes to the code look good enough to merge, but I'd recommend squashing the commits and rebasing on latest `main` just to be sure that no new `ISC001` violations have been introduced since the pull request was opened.

2023-06-29 16:28 UTC, nstarman approved these changes
Thanks @Maia-jp !

2023-06-29 17:11 UTC, eerovaher commented
The changes look good, but the CI image test failed for unrelated reasons and that's blocking the merge. Rebasing on current `main` should allow the CI tests to succeed, or maybe @pllim has a better idea on how to proceed.

2023-06-30 15:52 UTC, eerovaher commented
I've rebased this and all the required tests have succeeded, so this should be good to merge.

2023-06-30 15:59 UTC, dhomeier commented
> I think these are all very uncontroversial. Most probably arose during the `black` PR. A nice cleanup!

Yes, typically artefacts from `black` merging lines – is there some configuration available in `black` to prevent this, or are we just relying on `ruff` cleaning up after `black` from now on?

2023-06-30 16:01 UTC, dhomeier approved these changes
Good to go for `io.ascii`, thanks!

2023-07-01 13:10 UTC, nstarman commented
> > I think these are all very uncontroversial. Most probably arose during the `black` PR. A nice cleanup!
> 
> 
> 
> Yes, typically artefacts from `black` merging lines – is there some configuration available in `black` to prevent this, or are we just relying on `ruff` cleaning up after `black` from now on?

I think it's actually a trickier problem since ruff runs before black (as is recommended). So if Black introduces one of these issues I don't think it's caught until a cron job runs. I don't think that should stop us from merging this PR, but we should think how to detect this in the future. Of course, if people have pre-commit installed on their local machine then pre-commit runs locally and then on GitHub and will catch any issue on ruff's second run.

2023-07-03 17:37 UTC, eerovaher commented
> ...is there some configuration available in `black` to prevent this, or are we just relying on `ruff` cleaning up after `black` from now on?

Black has the `--experimental-string-processing` option that turns on [improved string processing](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#improved-string-processing), but using it alone is deprecated. It is possible to use it with the [`--preview` option](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style), but that also turns on a few more features. But [APE-20 specifies that `astropy` uses Black with its default settings](https://github.com/astropy/astropy-APEs/blob/main/APE20.rst#implementation). Letting Ruff check for ISC001 violations should work fine in practice and seems to be simpler than going through the process of updating the APE.

> ...So if Black introduces one of these issues I don't think it's caught until a cron job runs...

If Black edits the code then that causes the `pre-commit.ci` check to fail.

2023-07-03 19:01 UTC, nstarman commented
> > ...So if Black introduces one of these issues I don't think it's caught until a cron job runs...

> If Black edits the code then that causes the pre-commit.ci check to fail.

True! wonderful.

2023-07-03 19:08 UTC, nstarman commented
@taldcroft @saimn @larrybradley @WilliamJamieson @eerovaher are we good to merge?

2023-07-03 20:58 UTC, eerovaher commented
I was the one who rebased this so I'd prefer not to review. But if I would've had any objections I would not have rebased.

2023-07-03 21:57 UTC, dhomeier commented
> Black has the `--experimental-string-processing` option that turns on [improved string processing](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#improved-string-processing), but using it alone is deprecated. It is possible to use it with the [`--preview` option](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style), but that also turns on a few more features. But [APE-20 specifies that `astropy` uses Black with its default settings](https://github.com/astropy/astropy-APEs/blob/main/APE20.rst#implementation). Letting Ruff check for ISC001 violations should work fine in practice and seems to be simpler than going through the process of updating the APE.
> > ...So if Black introduces one of these issues I don't think it's caught until a cron job runs...
> 
> If Black edits the code then that causes the `pre-commit.ci` check to fail.

🤯 And there is no APE for Ruff usage... Well, hopefully broken string concatenations in new commits should be easily enough spotted; and once merged into single strings, black would leave them alone, right?

2023-07-04 10:56 UTC, taldcroft approved these changes
LGTM

2023-07-04 13:46 UTC, nstarman commented
> once merged into single strings, black would leave them alone, right?

It won't break up a string, but it might move the whole string to a new line.

2023-07-04 13:49 UTC, nstarman commented
We now have three explicit, and one implicit approval, so I'll merge by end of day unless someone has an objection

2023-07-04 13:56 UTC, dhomeier approved these changes
Did not find any new broken strings in `main` since rebasing either.

2023-07-20 17:32 UTC, merged