Fix broken test in ndslicing
astropy/astropy pull request #14924
Opened 2023-06-06 14:49 UTC by mwcraig

The former comparison was identified in astropy/astropy#14920 as a comparison that wasn't tested. "is" was not the appropriate comparison anyway, and comparing a dict to an UnknownUncertainty was also not sensible.

### Description

This pull request is to address a (failing) comparison in the `NDSlicing` tests that
was quietly failing.

Addresses the `nddata` part of #14920.

2023-06-06 17:57 UTC, eerovaher requested changes
In #14919 the [rule B015](https://beta.ruff.rs/docs/rules/#flake8-bugbear-b) was removed from the global Ruff ignore list and was added to the `nddata` sub-package ignore list because of the comparison this pull request addresses, so `.ruff.roml` also needs to be edited so that Ruff will enforce B015 in `nddata`: https://github.com/astropy/astropy/blob/0a71105fbaa71439206d496a44df11abc0e3ac96/.ruff.toml#L297-L298

2023-06-13 14:19 UTC, mwcraig commented
@eerovaher -- I *think* I correctly change the ruff config file.

@eerovaher and @pllim -- if this looks good please don't merge it. I'm meeting with @bmorris3 this afternoon and would like to use this PR to walk him through his first merge as an `nddata` maintainer.

2023-06-13 14:20 UTC, pllim commented
There is conflict, need a rebase. Good luck!

2023-06-13 14:23 UTC, mwcraig commented
Now it is actually fixed, I think 😬

2023-06-13 16:08 UTC, mwcraig commented
pre-commit.ci autofix

2023-06-13 18:15 UTC, bmorris3 approved these changes
Looks good to me.

2023-06-13 18:15 UTC, merged

2023-06-13 19:25 UTC, pllim commented
@mwcraig / @bmorris3 -- Also an excellent opportunity to try your hand at manual backports. 😉

2023-06-13 19:25 UTC, pllim commented
p.s. Probably caused by Ruff stuff since we don't backport those.

2023-06-13 19:46 UTC, mwcraig commented
> @mwcraig / @bmorris3 -- Also an excellent opportunity to try your hand at manual backports. 😉 

Ok, can look in the morning

2023-06-14 18:55 UTC, mwcraig commented
This is getting backported to the 5.3.x branch, not 5.0.x, right?

2023-06-14 18:55 UTC, mwcraig commented
Also, should I just backport the test change or also the ruff configuration?

2023-06-14 19:40 UTC, pllim commented
@mwcraig 

> This is getting backported to the 5.3.x branch, not 5.0.x, right?

Yes, just 5.3.x because this is not really a "critical bug fix that we must put in LTS", right?

> should I just backport the test change or also the ruff configuration?

There is no need to backport ruff. I actually think it is the ruff stuff that is causing conflict, not the actual fix.