Always convert explicitly longitudes and latitudes to 'rad' instead of 'radians'
astropy/astropy pull request #14940
Opened 2023-06-13 15:50 UTC by HealthyPear

### Description

When converting between coordinate frames what is currently happening is that `lon` and `lat` attributes get converted to `radians`, which depending on the current unit registry might or might not be defined as an alias to `rad`.

Luckily, the latter is always defined as the official name for radians, so it makes sense to make sure that we convert these quantities always using the guaranteed unit name.

Fixes #14580.

Note that #14933 was originally opened to update the documentation and recall the user to use a context manager when enabling e.g. CDS units (which do not define "radians", only "rad"). This PR should be the effective fix, but I think it still makes sense to have also the older PR.

Fixes #14580

2023-06-13 18:10 UTC, eerovaher requested changes
Overall this looks like a good bugfix, but it needs to be updated before it can be merged.

The `pre-commit.ci` test is failing. If you follow [our instructions how to enable `pre-commit` in your local repository](https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit) then commits that would fail `pre-commit.ci` could be prevented from being created, and `pre-commit` can often automatically fix the problem that would cause `pre-commit.ci` to fail.

For bugfix pull requests I would prefer the test that reveals the bug to be in the first commit and the bugfix in the second. If done in that order it is simpler to verify that the bug indeed exists.

Some of the edited lines are not being executed during the tests. It would be good to have new tests to check those lines of code too.

Commit messages should be understandable on their own. Only adding a link to a issue on GitHub is not informative enough.

2023-08-25 20:08 UTC, HealthyPear commented on astropy/units/tests/test_units.py
> +def test_cds_with_coordinates_transformations():
in which module should I place it?

2023-08-25 20:11 UTC, HealthyPear commented on astropy/units/tests/test_units.py
> +def test_cds_with_coordinates_transformations():
oh `test_transformations.py`

2023-08-25 20:13 UTC, HealthyPear commented on astropy/units/tests/test_units.py
> +def test_cds_with_coordinates_transformations():
done

2023-08-25 20:13 UTC, HealthyPear commented on docs/changes/coordinates/14940.bugfix.rst
> +for which 'radians' might not be defined.
done

2023-08-25 20:14 UTC, HealthyPear commented
Please, be aware that I have force-pushed the code-review commits in order to cleanup my branch's history.

2023-10-02 22:06 UTC, eerovaher requested changes
The first commit in a bugfix pull request should add a unit test that triggers the bug, the second commit should then fix it. The reason is that then it is very simple to verify that the new test actually triggers the bug, and that the fix actually addresses it. See also [relevant `astropy` developer documentation](https://docs.astropy.org/en/latest/development/workflow/git_edit_workflow_examples.html#test-first-please).

The commit messages should also be improved. At the very least they shouldn't be factually wrong. For example, 661e91017ac1f0916c3a001382de06eadd5ee64d claims that a unit test is being moved under coordinates testing. That by itself is not very useful because that much could be seen just from the commit contents. It would be much more interesting to know why a test is being moved. But actually nothing is being moved because the unit test being added to `coordinates` testing is a brand new one. See also [the description of a good commit message in the Pro Git book](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) (under the Commit Guidelines section).

2023-10-02 22:06 UTC, eerovaher commented on astropy/coordinates/tests/test_transformations.py
> +    from astropy.coordinates import SkyCoord
The fact that `SkyCoord` is not being imported in this file suggests that perhaps `astropy/coordinates/tests/test_celestial_transformations.py` would be a more suitable location.

2023-10-02 22:06 UTC, eerovaher commented on astropy/coordinates/tests/test_transformations.py
> +    from astropy.units import cds
As many imports as possible should be done in the beginning of the file.

2024-02-23 05:35 UTC, closed without merging