Adjust IERS update workflow to open PRs against v5.0.x and v5.3.x
astropy/astropy pull request #15013
Opened 2023-07-03 10:18 UTC by astrofrog

This will be needed once https://github.com/astropy/astropy/pull/14819 is merged. I have tested this on my local fork and it seems to work (including on the LTS branch).

2023-07-03 14:02 UTC, pllim requested changes
I dunno... I thought you would have this workflow in the workflow file directly in that branch. That way, we don't have to remove this on main again when we drop LTS in a few months.

2023-07-03 14:13 UTC, astrofrog commented
Cron jobs can only run on main - but we do check out the correct branches

2023-07-03 14:19 UTC, pllim commented
Okay, in that case, maybe a follow-up issue milestoned to 6.0 so we remember to disable it when LTS is done. Thanks!

2023-07-06 15:09 UTC, pllim approved these changes
LGTM. Thanks!

2023-07-06 15:10 UTC, pllim commented
I won't merge yet since you need that other thing to get in first.

2023-07-07 21:39 UTC, pllim commented
There is a conflict. Please rebase, then we can merge. Thanks!

2023-07-07 22:46 UTC, astrofrog commented
@pllim - rebased!

2023-07-07 22:47 UTC, pllim approved these changes
Thanks!

2023-07-08 00:00 UTC, merged