Address Ruff Rule PT021 violation in astropy/samp/tests/test_client.py
astropy/astropy pull request #15033
Opened 2023-07-06 14:07 UTC by Alpha-Ursae-Minoris

### Description

Rule PT021 checks whether request.addfinalizer is used and suggests to "use yield instead of request.addfinalizer". 

I replaced the only use of request.addfinalizer in astropy/samp/tests/test_client.py and removed the rule in the .ruff.toml file.

Running `ruff --select=PT021 --statistics astropy/` now yields no violations.

This pull request is to address Issue #14818

2023-07-06 15:01 UTC, pllim submitted a review, later dismissed
I don't think your fix is working:

`astropy\samp\tests\test_client.py::test_reconnect - astropy.samp.errors.SAMPWarning: Another SAMP Hub is already running. Start-up process aborted.`

2023-07-06 15:02 UTC, nstarman commented
Thanks @Alpha-Ursae-Minoris for the PR.
Check out https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#yield-fixtures-recommended, I think that indicates that there needs to be cleanup post-yield.

2023-07-06 15:02 UTC, pllim commented
Also PT021 is not listed under #14818 check list.

2023-07-06 15:38 UTC, Alpha-Ursae-Minoris commented
Thank you for your the helpful link @nstarman. Now all the tests in astropy/samp/ run successfully locally using -rs.

2023-07-06 16:42 UTC, Alpha-Ursae-Minoris commented
@pllim I have now added PIE804 from the #14818 check list.

2023-07-06 17:57 UTC, pllim commented
Thanks! A few things:

* Please also update ruff file with PIE804 stuff
* Please fix pre-commit failure
* Please do not create merge commit in your PR history, instead use `rebase` (let us know if you need help with this)
* Please squash all your commits into one commit

2023-07-06 19:01 UTC, Alpha-Ursae-Minoris commented
Thanks for the pointers @pllim, they should be implemented correctly now. Please take a look and let me know if there's anything else that needs attention.

2023-07-06 19:07 UTC, pllim commented
Thanks! mpldev failure is unrelated. The diff LGTM now but I'll let @nstarman or @eerovaher approve, since they know about Ruff way more than I do.

2023-07-06 20:48 UTC, eerovaher requested changes
This pull request improves `astropy` by ensuring it complies with two more Ruff rules, but differently from @pllim I think there should be separate commits for both rules.

2023-07-06 20:48 UTC, eerovaher commented on astropy/samp/tests/test_client.py
> -    request.addfinalizer(my_hub.stop)
This was the only line that used `request`, so `samp_hub` shouldn't be asking for it anymore.

2023-07-06 20:48 UTC, eerovaher commented on astropy/samp/tests/test_client.py
> +    yield my_hub
This fixture didn't return `my_hub`, so it shouldn't yield it either.
```suggestion
    yield
```

2023-07-07 15:37 UTC, Alpha-Ursae-Minoris commented
@eerovaher I have modified the code and commits as you suggested.

2023-07-07 18:26 UTC, eerovaher requested changes
This is almost ready for merging, but the commit concerning `PT021` should change the line https://github.com/astropy/astropy/blob/001dfa89a03e9d2c6cdc5bff4f90dee69f1d9060/astropy/samp/tests/test_client.py#L34 to `def samp_hub():`
(The line in question is far enough from the code changes that GitHub UI doesn't let me write a code suggestion).

2023-07-07 18:44 UTC, Alpha-Ursae-Minoris commented
@eerovaher Apologies for the oversight, should be fixed now.

2023-07-07 19:01 UTC, eerovaher approved these changes
Despite being a small pull request in terms of the number of edited lines, it nonetheless manages to improve `astropy` by addressing two Ruff rules.

2023-07-07 19:11 UTC, merged