Removing deprecated code for _model_to_fit_params
astropy/astropy pull request #15461
Opened 2023-10-10 21:29 UTC by Amenaske

### Description

This pull request is to address the removal of deprecated code in the modeling subpackage for the fitting module.

Fixes #15455

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2023-10-10 21:34 UTC, pllim commented
Thanks! Still need:

* Change log
* Update usage in `docs/modeling/new-fitter.rst`

2023-10-10 21:37 UTC, pllim commented
I also think this needs to be done together with `_fitter_to_model_params`.

2023-10-11 12:40 UTC, WilliamJamieson requested changes

2023-10-11 12:40 UTC, WilliamJamieson commented on astropy/modeling/fitting.py
> -
As @pllim pointed out, the `_filter_to_model_params` function should be removed at the same time as this. They are a matched pair of related functions.

2023-10-11 15:34 UTC, pllim commented
@Amenaske , are you interested to address the review comments? Given that our v6.0 feature freeze is fast approaching, if you do not have time or interest to wrap this up in a few days, I can take over. Please let me know. Thank you!

2023-10-11 20:29 UTC, Amenaske commented
Yes, I'll address the review comment.

2023-10-12 01:23 UTC, WilliamJamieson approved these changes

2023-10-12 01:25 UTC, WilliamJamieson submitted a review, later dismissed
The docs still need to be updated.

2023-10-12 21:26 UTC, pllim commented
Since we're fast approaching feature freeze, I will just clean this one up and wrap it up. Hope you don't mind. Thanks!

2023-10-12 21:41 UTC, pllim approved these changes
Thanks!

2023-10-12 22:00 UTC, merged