Don't upload to PyPI on workflow dispatch
astropy/astropy pull request #15535
Opened 2023-10-26 15:46 UTC by astrofrog

Just a small tweak to the publish workflow - now that when we do workflow_dispatch we default to building against Numpy dev, I don't think we want to upload to PyPI also when using workflow_dispatch. I think it makes sense to keep workflow_dispatch as a developer thing anyway, and not to make actual stable releases.

2023-10-26 23:09 UTC, mhvk approved these changes
That certainly makes sense to me, but I'll let @saimn review too, as perhaps I'm missing something.

2023-10-27 16:21 UTC, pllim requested changes
I am not sure if I like this now that I think about it more. In several occasions, I need to fix downstream job fast (or requested by another downstream maintainer), so I used the dispatch to generate new dev wheel on the fly.

2023-10-27 16:22 UTC, pllim commented
Also I don't think this is upload to PyPI but to the Anaconda wheel repo, right?

2023-10-27 16:23 UTC, pllim approved these changes
No nvm... I missed that Anaconda is a different setting. Let's just get this in then. Thanks!

2023-10-27 16:23 UTC, merged