Improve `io.ascii` error message when there is mismatch between converter type and column type
astropy/astropy pull request #15991
Opened 2024-02-04 21:29 UTC by orionlee

### Description

This pull request is to make the `TypeError` message clearer in reading ascii tables, when there is a mismatch between converter type and column type.

For the scenario in #15989, the error message is changed from
```
TypeError: converter type does not match column type
```
to:
```
TypeError: converter type StrType does not match column type IntType for column oid
```
stating the offending column and the specific type mismatch.

Test changes:
- so far none. So far I can create the error in the scenario in #15989. I don't know enough of the `Table` internals to create a unit test for it.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-02-05 07:01 UTC, neutrinoceros approved these changes
This is definitely clearer, nice catch !

2024-02-12 17:23 UTC, taldcroft commented
@orionlee - Documenting a functional test following the scenario in #15989 will be sufficient. Please do that and put the results in a `Functional testing` section in the top-level PR description. Given the very narrow scope of this we don't need a new unit test.

2024-02-12 17:27 UTC, taldcroft requested changes
Thanks @orionlee looks generally good. There are just a few small things to get this merged.

The `15991.bugfix.rst` file should be changed to a feature `15991.feature.rst`. Having this as a bug fix implies it could be back-ported, but that is not desirable here. In general making exception messages more useful to users is an enhancement feature.

2024-02-12 17:27 UTC, taldcroft commented on docs/changes/io.ascii/15991.bugfix.rst
> +Clearer error message in reading ascii tables when there is
Use `ASCII` everywhere not `ascii`.

2024-02-12 18:50 UTC, orionlee commented
@taldcroft changelog is updated. A new Functional Testing section is added to PR description.

2024-02-12 19:28 UTC, taldcroft approved these changes
Looks good thanks @orionlee!

2024-02-12 19:28 UTC, merged