MAINT: The __init__ cols argument should be set to None in TableColumns
astropy/astropy pull request #16092
Opened 2024-02-22 14:56 UTC by MridulS

While trying to debug https://github.com/astropy/astropy/issues/16089 I ran into this bit of code.

`def __init__(self, cols={}):` can have unintended consequences, not sure if there is a specific reason for this?

2024-02-22 15:09 UTC, WilliamJamieson commented on astropy/table/table.py
> +            cols = {}
```suggestion
        cols = {} if cols is None else cols
```
I would suggest something like
```python
        cols = cols or {}
```
but things like empty lists, empty tuples, or other "falsy" objects would  get remapped to `{}` and I don't know the consequences of that.

2024-02-22 15:11 UTC, neutrinoceros approved these changes
I agree with this change. More generally, there seem to be a lot of violations to [B006](https://docs.astral.sh/ruff/rules/mutable-argument-default/) in the code base, which doesn't have any open issue that I could find at the moment. It might be worth opening one now.

2024-02-22 15:12 UTC, WilliamJamieson commented on astropy/table/table.py
> +    def __init__(self, cols=None):
@pllim I don't think this is an API change as the only change would be loosing possible memory of the default between different initializations of the `TableColumns` objects. This would likely be causing bugs rather than being exploited by something as that would be a very unreliable side effect to depend on.

2024-02-22 15:13 UTC, WilliamJamieson commented
> I agree with this change. More generally, there seem to be a lot of violations to [B006](https://docs.astral.sh/ruff/rules/mutable-argument-default/) in the code base, which doesn't have any open issue that I could find at the moment. It might be worth opening one now.

Agreed, these cause all sorts of subtle, difficult to replicate bugs.

2024-02-23 06:56 UTC, MridulS commented
>  Did this API allow passing in cols=None as some sort of special case before? Because that would be an API change, no?

I tried grepping in astropy's codebase for this kind of usage but couldn't find any. I doubt this was by design? This was last touched in 2011 https://github.com/astropy/astropy/commit/7d5d1643fa431257d6d1e487bcb00cead288fbb6 😅

2024-02-23 08:40 UTC, MridulS commented
cleaned up couple of other places in the tables codebase

2024-02-23 11:10 UTC, taldcroft requested changes

2024-02-23 11:10 UTC, taldcroft commented on astropy/table/table.py
> +    def __init__(self, cols=None):
If you look at the code there is literally no way for the value of `cols` to be updated in-place unless the `OrderedDict` initializer does it (which is not the case). So in reality making this change is not preventing any potential bugs, but I agree this pattern should be avoided.

Unlike the above two examples, passing `None` here would just cause a crash. My style preference in this case is below. It takes one more line but I think it is more readable and does not include an odd null statement `col = col`.
```
if cols is None:
    cols = {}
```

2024-02-23 13:48 UTC, eerovaher commented
Ruff rule [B006](https://docs.astral.sh/ruff/rules/mutable-argument-default/) has very few violations in `table`:
```
$  ruff check --select B006 --statistics astropy/table/
6	B006	[*] Do not use mutable data structures for argument defaults
```
It would be best to address all of them, by changing the defaults or adding `noqa` instructions where needed.

2024-02-26 13:52 UTC, neutrinoceros commented
I opened #16107 so that the broader discussion about fixing B006 everywhere survives this being merged

2024-02-26 14:09 UTC, MridulS commented
@eerovaher I think all the other instances of `B006` here are tricky, as @taldcroft pointed out in one example. I guess I can either just close this PR and create a new one which fixes or adds `noqa` all across astropy? It would less noise with the `ruff.toml` file that way 😅

2024-02-26 14:55 UTC, MridulS commented
continued in https://github.com/astropy/astropy/pull/16109

2024-02-26 14:55 UTC, closed without merging