Deprecate `utils.xml.unescaper.unescape_all()`
astropy/astropy pull request #16115
Opened 2024-02-27 16:56 UTC by eerovaher

### Description

The function has been unused since 4ef6c24b186694658be2300f16ea1a5b1c038eb2. [It is a part of the public API](https://docs.astropy.org/en/stable/api/astropy.utils.xml.unescaper.unescape_all.html#astropy.utils.xml.unescaper.unescape_all), so we cannot remove it immediately.

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-02-27 17:00 UTC, pllim requested changes
It is still used over at `astroquery.vo_conesearch`. I still run the validator daily.

https://github.com/search?q=repo%3Aastropy%2Fastroquery%20unescape_all&type=code

2024-02-27 17:19 UTC, eerovaher commented
I don't think writing or parsing XML is something `astropy` should be expected to do. Although some XML-related utilities might be useful for us, all functionality in `utils.xml` that we are not using ourselves should be removed.

2024-02-27 17:26 UTC, pllim commented
I don't know what else downstream is using this and I don't have time to investigate right now. I feel like cleaning up `utils.xml` shouldn't be a priority right now given all the other open issues.

But if you are passionate about this, please open up a discussion on astropy-dev for `utils.xml` in general. Thanks!

2024-03-14 21:31 UTC, eerovaher commented
It's best to ask the `astroquery` maintainers first: @bsipocz @ceb8 @keflavich

2024-03-14 21:39 UTC, bsipocz commented
Has this caused any issues ever? If not, then maybe don't fix that is not broken causing all kinds of issues downstream. There is a ton of historical baggage in the library, and if super-specific modules like cosmology can stay, then this should, too.

As for astroquery, we're not interested in taking over any XML functionality, especially as the conesearch should eventually make its way upstream to pyvo. But overall, my opinion is as it was in the past year when uncalled-for cleanup happened in  io.votable causing a lot of issues for PRs, that please leave the VO and adjacent (e.g. XML) stuff in astropy alone.

2024-04-16 13:34 UTC, closed without merging