TST: add a test job for numpy 2.0.0 pre-releases
astropy/astropy pull request #16249
Opened 2024-03-29 16:23 UTC by neutrinoceros

### Description

Numpy 2.0.0rc1 is now imminent (according to https://github.com/numpy/numpy/issues/24300#issuecomment-2027392563)
As I noted in https://github.com/astropy/astropy/pull/16229, we're not currently testing against numpy 2.0.0 pre-releases, and testing against the dev branch has proven to be an insufficient proxy, so I propose we introduce a new (temporary) test job specifically focused on covering this case.
I've tested this branch on my fork and pinning numpy to version `2.0.0b1`, but this may become outdated very soon, so I'll keep this as a draft until one of the following happens:
- numpy 2.0.0rc1 is out and I can update this PR
- the week-end is over

Maintainers should feel free to push to this branch if there's a need for getting this in earlier.
I don't *think* I'll be actively working on this over the weekend, but I'll still happily respond to pings, so please *do* ping me if you need to update this so I know to be careful if I want to push again myself.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-03-29 19:56 UTC, pllim requested changes
Not sure if this is necessary. We already test against pre-releases daily at https://github.com/astropy/astropy/blob/878cc772cd648300367930707f7f6a1f1e5e4172/.github/workflows/ci_cron_daily.yml#L51 . We can also run it as needed via workflow dispatch. If you want to run that job in PR, you can use "Extra CI" label.

2024-03-30 16:04 UTC, neutrinoceros commented
Oh, I wasn't aware we did this, thanks for pointing it out !
I note however that daily cron jobs are *not* picking up numpy 2.0.0b1 at the moment (someone else from the stack of dependencies we're grabbing must be pinning it ?), so right now it might still have some value to add a job *just* for numpy 2.0. That being said, I should also note that, when I opened this PR yesterday, I thought I was seeing another regression when testing locally against numpy `maintenance/2.0.x`, but it turned out to be a different problem which had nothing to do with numpy, so there's also less of a need for this job than I previously thought.

Anyway, I propose we re-assess on what to do with this PR on Monday, and maybe by then we'll even see an actual release candidate ?

2024-03-30 16:13 UTC, astrofrog commented
We could also just add this to the integration testing repo?

2024-03-30 17:18 UTC, neutrinoceros commented
Sure ! where's that ?

2024-04-01 20:02 UTC, pllim commented
Ah, right. It is at https://github.com/astropy/astropy-integration-testing

I kicked off https://github.com/astropy/astropy-integration-testing/actions/runs/8512968778/job/23315688712 but since we pinned `numpy<2` for astropy v6.0.1 and we do not yet have astropy v6.1rc, it is not picking up numpy 2.0rc. FYI.

2024-04-02 08:54 UTC, neutrinoceros commented
> since we pinned numpy<2 for astropy v6.0.1 and we do not yet have astropy v6.1rc, it is not picking up numpy 2.0rc.

`2.0.0rc1` actually still matches `<2`, but as I said in https://github.com/astropy/astropy/pull/16249#issuecomment-2028183354, something else in the env must be pinning it harder (possibly scipy). Anyway, it looks like we're already doing everything we can on our side and there don't seem to be actual hidden incompatibilities to catch any more so let's just close this for now. Thank you both !

2024-04-02 08:54 UTC, closed without merging