Added a 'perf' changelog entry type
astropy/astropy pull request #16694
Opened 2024-07-10 08:59 UTC by astrofrog

As discussed in https://github.com/astropy/astropy/issues/16679

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-07-10 09:53 UTC, neutrinoceros requested changes
pre-commit will still invalidate a fragment named, for instance `1.perf.rst`, but the fix is simple enough:
```patch
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 64cbacf354..e663730c60 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -114,10 +114,10 @@ repos:
         name: changelog filenames
         language: fail
         entry: >-
-          changelog files must be named <sub-package>/####.(bugfix|feature|api).rst
+          changelog files must be named <sub-package>/####.(bugfix|feature|api|perf).rst
           or ####.other.rst (in the root directory only)
         exclude: >-
-          ^docs/changes/[\w\.]+/(\d+\.(bugfix|feature|api)(\.\d)?.rst|.gitkeep)
+          ^docs/changes/[\w\.]+/(\d+\.(bugfix|feature|api|perf)(\.\d)?.rst|.gitkeep)
         files: ^docs/changes/[\w\.]+/
       - id: changelogs-rst-other
         name: changelog filenames for other category
```

2024-07-10 13:50 UTC, astrofrog commented
@neutrinoceros - fixed, thanks!

2024-07-10 16:39 UTC, neutrinoceros approved these changes

2024-07-10 17:15 UTC, pllim commented
I think there isn't any merged PRs that need their change log moved. But should we add a note to these ones?

https://github.com/astropy/astropy/pulls?q=is%3Apr+is%3Aopen+label%3APerformance+-label%3Ano-changelog-entry-needed

2024-07-10 17:29 UTC, nstarman approved these changes
SGTM!

2024-07-10 18:29 UTC, eerovaher commented
Announcing performance improvements in the change log can be good, but we should write down a guideline somewhere that in order for a pull request to be announced in the change log in the performance category there must exist some code example using only the public API that has been sped up by e.g. 10% (the number is to be decided here).

2024-07-10 19:07 UTC, nstarman commented
I would say even 2-3% improvements. These add up over time!

2024-07-10 19:08 UTC, pllim commented
@eerovaher , are you saying that this PR also needs to update dev docs?

2024-07-10 19:37 UTC, astrofrog commented
If a performance improvement isn't important enough to be in the changelog maybe it doesn't warrant a pull request? 🙃

2024-07-10 19:43 UTC, pllim commented
I think at least this needs updating? https://docs.astropy.org/en/latest/development/development_details.html#add-a-changelog-entry

2024-07-10 19:51 UTC, eerovaher commented
@nstarman [wrote](https://github.com/astropy/astropy/pull/16694#issuecomment-2221237678):

> I would say even 2-3% improvements. These add up over time! But maybe others feel 5% is a better number to merit the changelog?

The smaller the speedup, the more difficult it is to distinguish the signal from the noise. If the speedup is too small then measuring it reliably is a waste of time and effort.

@pllim [asked](https://github.com/astropy/astropy/pull/16694#issuecomment-2221238897):

> @eerovaher , are you saying that this PR also needs to update dev docs?

All the other change log entry categories are documented, there's no reason for the performance category to be any different.

@astrofrog [wrote](https://github.com/astropy/astropy/pull/16694#issuecomment-2221282725):

> If a performance improvement isn't important enough to be in the changelog maybe it doesn't warrant a pull request? 🙃

Some refactoring pull requests might have small performance implications. In some cases these serendipitous speedups might be large enough to be announced.

2024-07-10 20:19 UTC, astrofrog commented
Maybe the threshold should just be a 'measurable' performance improvement.

2024-07-11 09:54 UTC, astrofrog commented
I've added a note to the contributor docs, and also have added in both cases that the improvement has to be measurable using public API, which I think is a sufficient threshold.

2024-07-11 10:25 UTC, Cadair approved these changes

2024-07-11 14:59 UTC, pllim approved these changes
OK let's do it then. Thanks, all!

2024-07-11 14:59 UTC, merged