Made the api for CompoundModel.with_units_from_data() public and upda…
astropy/astropy pull request #16723
Opened 2024-07-14 18:12 UTC by DavidVFiumano

Fixed issue 16711 by making the API for CompoundModel.with_units_from_data() public and updated associated documentation to reflect the change.

This is a draft, I'll make another commit with a changelog entry in a few minutes.

This is my first pull request to this repository - if I've made a mistake please let me know and I'll fix it as soon as I can.

Thank you,
- David Fiumano

### Description

This pull request is to address issue #16711.

Fixes #16711 

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-07-15 09:05 UTC, neutrinoceros commented
Hi @DavidVFiumano, thanks for your contribution
While the change is simple, it should be noted that, as mentionned in https://github.com/astropy/astropy/issues/16711#issuecomment-2225913576, it is also an opportunity to give these keys clearer names. 
Maybe @astrofrog can argue that these names are as good as it gets, but in any case this needs to be discussed before we can merge your PR, since we cannot go back after some part of the API has been made public (at least not easily).
Thank you for your understanding !

2024-07-15 09:14 UTC, astrofrog commented
I also want to check whether we *actually* need these keyword arguments in the first place, or if there is any way we can do without them if a user calls them directly.

2024-10-16 15:56 UTC, WilliamJamieson requested changes
The "private" keyword argument still needs to be left as an option and deprecated, without this it is possible to break downstream code.

2024-10-16 15:56 UTC, WilliamJamieson requested changes
The "private" keyword argument still needs to be left as an option and deprecated, without this it is possible to break downstream code.

2025-01-12 05:38 UTC, closed without merging