Fix WCS world axis selection in `fit_parallel_dask`
astropy/astropy pull request #17041
Opened 2024-09-19 14:59 UTC by Cadair

### Description

This fix uses the axis correlation matrix to select which world axes corresponding to the fitting axes supplied as array indicies.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-09-19 15:00 UTC, Cadair commented
I guess I should probably write a regression test

2024-09-26 09:51 UTC, astrofrog requested changes
I think this looks reasonable but yes having a regression test looks good. It'd also be good to test we raise an error if there are any ambiguity due to the correlation matrix. Also see below for a comment related to this.

2024-09-26 09:51 UTC, astrofrog commented on astropy/modeling/_fitting_parallel.py
> +            np.argwhere(world.axis_correlation_matrix[:, fpa])[:, 0][0]
Looks like you are assuming there is a single match because of the ``[:, 0]``?

2024-10-21 15:04 UTC, Cadair commented
I spent a couple of hours trying to write a unit test for this and went slowly mad, so I have given up for now.

2024-10-25 10:35 UTC, astrofrog commented
The CircleCI failure should be unrelated

2024-10-25 15:01 UTC, astrofrog approved these changes

2024-10-25 15:01 UTC, merged