BUG: let Time.ptp emit a deprecation warning against any version of numpy
astropy/astropy pull request #17212
Opened 2024-10-19 07:44 UTC by neutrinoceros

### Description
Follow up to https://github.com/astropy/astropy/pull/16212, as [requested by @eeravaher](https://github.com/astropy/astropy/pull/16212#issuecomment-2423279876)

At the time #16212, I aknowledged making the warning condition was a mistake (https://github.com/astropy/astropy/pull/16212#discussion_r1643864256) so I'm considering this a bugfix.

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-10-19 11:43 UTC, mhvk approved these changes
Looks good, thanks!

2024-10-21 16:40 UTC, eerovaher requested changes
Backporting this can introduce a new deprecation warning in a bugfix release to users who are still using `numpy` < 2, which is not allowed by [APE 2](https://github.com/astropy/astropy-APEs/blob/6aa0871f20e0d16dcc60e75988e8ad34a9a3bd1f/APE2.rst?plain=1#L137). Therefore the method must be marked as deprecated since `astropy` v7.0 and the new change log entry should point out that the deprecation announced in v6.1 was botched.

2024-10-21 17:34 UTC, neutrinoceros commented
Thanks for pointing this out. Addressed.

2024-10-21 17:51 UTC, eerovaher approved these changes

2024-10-21 18:02 UTC, merged

2024-10-21 18:02 UTC, pllim commented
Thanks, all!