Refactor from_repr method to avoid eval usage (S307)
astropy/astropy pull request #17253
Opened 2024-10-25 16:57 UTC by Rekaniry

### Description

This pull request refactors the `from_repr` method in the `Parameter` class to eliminate the use of `eval()` in order to comply with rule S307 (suspicious eval usage). The test `test_Parameter_repr_roundtrip` has been updated accordingly.

Fixes #14818

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-10-25 17:15 UTC, neutrinoceros requested changes
Hola !
Thanks for working on this, but I'm afraid this approach misses the point: this test is really about checking whether the repr of a Parameter object correctly produces the code needed for instantiating said object. In fact, it seems to me that `eval` is the correct tool for that job. The reason `S307` (from *flake8-bandit*) exists is to detect security breaches where `eval` would be passed abritrary/unsanitized code, which isn't a concern here.

2024-10-27 17:23 UTC, pllim commented
If that eval is intentional and should stay, then at least a `# nosec` directive?

2024-10-27 17:36 UTC, neutrinoceros commented
Assuming you meant `# noqa: S307`, 👍🏻 
(otherwise, what's "noseq" ?)

2024-10-27 20:08 UTC, nstarman commented
> If that eval is intentional and should stay, then at least a `# nosec` directive?

Happy for a noqa PR that moves the ruff ignore from the global to package-specific settings.

2024-10-28 11:40 UTC, pllim commented
Whatever directive you use nowadays to ignore it. Used to be `# nosec` with `bandit`.

2025-04-25 05:42 UTC, closed without merging