cosmo: refactor layout, deprecate semi-private modules, add new io module
astropy/astropy pull request #17543
Opened 2024-12-13 16:34 UTC by nstarman

@mhvk, as we discussed offline. I've tried to make this change as easy to review as possible by breaking it into a sequence of atomic commits.

This PR has 3 parts:

1. `move(cosmo): X` commits move code into a private walled garden, re-exporting them exactly in place. There should be NO impact on public API.
2. `deprecate(cosmo): X` deprecates semi-private/semi-public modules. While Astropy states in certain places in the docs that these are private modules which may be moved, in practice they are public and people wrongly import from them directly. Therefore these commits deprecate their contents without removing them, which will happen for Astropy v8.
3. `feat: X` commits add something new and do impact the public API.

- [x] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

2024-12-13 22:21 UTC, nstarman commented
@mhvk everything is working except an annoying sphinx warning about `default_cosmology` not being found.
My sphinx is refusing to build the astropy docs, so if you could review this sans working docs build, that'd be great. I can find time later to wrangle the docs. Thanks!

![CleanShot 2024-12-13 at 17 20 01](https://github.com/user-attachments/assets/7a6e73c0-1c9f-4f55-9dfb-f7d963d2a672)

2025-01-08 23:35 UTC, nstarman commented
@mhvk, do you want me to edit the commit history in any way to make review easier?

2025-01-10 14:40 UTC, neutrinoceros requested changes
Thank you for carefully splitting this PR into atomic commits, it made reviewing, while somewhat tedious[^1], all the less confusing ! I also really like how the PR itself is atomic in a somewhat different sense; the merge commit will bring together all moving parts in a single clean go.

All of this seems reasonable to me, and I can certainly get behind your initial motivation for it; it's been brought up time and time again that the public/private boundary in this code base isn't clear to all users and caused both confusion and despair from both sides of the community (end users and core devs).
My one important concern is about deprecation warnings: I think we should avoid making any promises about *when* these deprecation will end (you never know if you'll be able to keep it, and even when it's possible to, we can also forget about it). On the other hand, it would be helpful to specify the "since" part of these messages.
Deprecated modules' docstrings should also avoid promising 8.0 as a due date.

[1]: though I can easily imagine that it's orders of magnitudes less tedious to read than it was to craft !

2025-01-10 14:40 UTC, neutrinoceros commented on astropy/cosmology/_src/tests/test_deprecated_modules.py
> +        warnings.catch_warnings(),
could you add a comment here (and in following similar tests) to explain why this filtering is needed ?

2025-01-11 02:22 UTC, nstarman commented
My sphinx still wont build docs! Tox, uv, all venvs fail. Perplexing.

2025-01-11 07:54 UTC, neutrinoceros approved these changes
Just a quick note to anyone interested: I was going to point out that deprecation warnings were lacking a `stacklevel` argument, but after experimentation I think only the default value (`stacklevel=1`) shows the entire message within the traceback, and nothing is gained from using a different value, so, approving as is, thank you !

Since I stepped in as a reviewer at the request of @nstarman in an attempt to relieve @mhvk's burden, I think we should at least wait for his blessing before we merge this.

2025-01-11 12:54 UTC, mhvk commented
No need to wait for me - for `cosmology` I've just been trying to help out (and failed to here).

2025-01-11 14:08 UTC, neutrinoceros commented
great ! now we "just" need to fix that RTD failure.
@pllim do you have any pointers ?

2025-01-11 17:14 UTC, pllim commented
The diff is too big for me to make a reasonable suggestion. But warnings are caused by broken refs. Did you make these "private" and hence undocumented? If so, stop linking to them in the public docs.

```
<unknown>:21: WARNING: py:obj reference target not found: astropy.cosmology.io [ref.obj]
<unknown>:23: WARNING: py:obj reference target not found: astropy.cosmology.funcs [ref.obj]
<unknown>:23: WARNING: py:obj reference target not found: astropy.cosmology.parameter [ref.obj]
<unknown>:23: WARNING: py:obj reference target not found: astropy.cosmology.core [ref.obj]
<unknown>:23: WARNING: py:obj reference target not found: astropy.cosmology.flrw [ref.obj]
<unknown>:23: WARNING: py:obj reference target not found: astropy.cosmology.io [ref.obj]
docs/cosmology/realizations.rst:309:<autosummary>:1: WARNING: py:obj reference target not found: astropy.cosmology.realizations.default_cosmology [ref.obj]
```

2025-01-13 18:23 UTC, nstarman commented
As a note: current failure is

"/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/17543/lib/python3.11/site-packages/astropy/cosmology/_src/default.py:docstring of astropy.cosmology._src.default.default_cosmology:1: WARNING: duplicate object description of astropy.cosmology._src.default.default_cosmology, other instance in api/astropy.cosmology.default_cosmology, use :no-index: for one of them"

What's mystifying is I have used `:no-index:`.

2025-01-13 18:40 UTC, pllim commented
`Message: 'Found additional options no-index in automodapi.'`

I don't think `:no-index:` is compatible with automodapi either. 😬

2025-01-13 18:41 UTC, pllim commented
I see that you attempted `:no-index:` in `realization` but I didn't see any for `default_cosmology`. Are they the same thing?

2025-01-18 20:11 UTC, nstarman commented
Thanks @neutrinoceros for the review of this large PR!

2025-01-18 20:18 UTC, merged